# -*- coding: utf-8 -*-

# Copyright (C) 2016 emijrp <emijrp@gmail.com>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
tambien se podrian crear listas de "futbolistas madrileños/sevillanos..." en funcion del lugar de nacimiento. Probar primero con los paises y luego ya iremos viendo

todos los fix q corrija, corregirlo en el script tb para q en la siguiente pasada traduzca bien las ocupaciones femeninas corregidas. Mejor usar globals y tirar de aqui
"""

import time
import urllib
import urllib.request
import urllib.parse

paises2qid = {
    'Afganistán': 'Q889', 
    'Albania': 'Q222', 
    'Alemania': 'Q183', 
    'Andorra': 'Q228', 
    'Angola': 'Q916', 
    'Antigua y Barbuda': 'Q781', 
    'Arabia Saudita': 'Q851', 
    'Argelia': 'Q262', 
    'Argentina': 'Q414', 
    'Armenia': 'Q399', 
    'Australia': 'Q408', 
    'Austria': 'Q40', 
    'Azerbaiyán': 'Q227', 
    'Bahamas': 'Q778', 
    'Bangladés': 'Q902', 
    'Barbados': 'Q244', 
    'Baréin': 'Q398', 
    'Bélgica': 'Q31', 
    'Belice': 'Q242', 
    'Benín': 'Q962', 
    'Bielorrusia': 'Q184', 
    'Birmania': 'Q836', 
    'Bolivia': 'Q750', 
    'Bosnia y Herzegovina': 'Q225', 
    'Botsuana': 'Q963', 
    'Brasil': 'Q155', 
    'Brunéi': 'Q921', 
    'Bulgaria': 'Q219', 
    'Burkina Faso': 'Q965', 
    'Burundi': 'Q967', 
    'Bután': 'Q917', 
    'Cabo Verde': 'Q1011', 
    'Camboya': 'Q424', 
    'Camerún': 'Q1009', 
    'Canadá': 'Q16', 
    'Catar': 'Q846', 
    'Chad': 'Q657', 
    'Chile': 'Q298', 
    'Chipre': 'Q229', 
    'Ciudad del Vaticano': 'Q237', 
    'Colombia': 'Q739', 
    'Comoras': 'Q970', 
    'Corea del Norte': 'Q423', 
    'Corea del Sur': 'Q884', 
    'Costa de Marfil': 'Q1008', 
    'Costa Rica': 'Q800', 
    'Croacia': 'Q224', 
    'Cuba': 'Q241', 
    'Dinamarca': 'Q35', 
    'Dominica': 'Q784', 
    'Ecuador': 'Q736', 
    'Egipto': 'Q79', 
    'El Salvador': 'Q792', 
    'Emiratos Árabes Unidos': 'Q878', 
    'Eritrea': 'Q986', 
    'Eslovaquia': 'Q214', 
    'Eslovenia': 'Q215', 
    'España': 'Q29', 
    'Estados Unidos': 'Q30', 
    'Estonia': 'Q191', 
    'Etiopía': 'Q115', 
    'Filipinas': 'Q928', 
    'Finlandia': 'Q33', 
    'Fiyi': 'Q712', 
    'Francia': 'Q142', 
    'Gabón': 'Q1000', 
    'Gambia': 'Q1005', 
    'Georgia': 'Q230', 
    'Ghana': 'Q117', 
    'Granada': 'Q769', 
    'Grecia': 'Q41', 
    'Guatemala': 'Q774', 
    'Guinea': 'Q1006', 
    'Guinea Ecuatorial': 'Q983', 
    'Guinea-Bisáu': 'Q1007', 
    'Guyana': 'Q734', 
    'Haití': 'Q790', 
    'Honduras': 'Q783', 
    'Hungría': 'Q28', 
    'India': 'Q668', 
    'Indonesia': 'Q252', 
    'Irak': 'Q796', 
    'Irán': 'Q794', 
    'Irlanda': 'Q27', 
    'Islandia': 'Q189', 
    'Islas Marshall': 'Q709', 
    'Islas Salomón': 'Q685', 
    'Israel': 'Q801', 
    'Italia': 'Q38', 
    'Jamaica': 'Q766', 
    'Japón': 'Q17', 
    'Jordania': 'Q810', 
    'Kazajistán': 'Q232', 
    'Kenia': 'Q114', 
    'Kirguistán': 'Q813', 
    'Kiribati': 'Q710', 
    'Kosovo': 'Q1246', 
    'Kuwait': 'Q817', 
    'Laos': 'Q819', 
    'Lesoto': 'Q1013', 
    'Letonia': 'Q211', 
    'Líbano': 'Q822', 
    'Liberia': 'Q1014', 
    'Libia': 'Q1016', 
    'Liechtenstein': 'Q347', 
    'Lituania': 'Q37', 
    'Luxemburgo': 'Q32', 
    'Madagascar': 'Q1019', 
    'Malasia': 'Q833', 
    'Malaui': 'Q1020', 
    'Maldivas': 'Q826', 
    'Malí': 'Q912', 
    'Malta': 'Q233', 
    'Marruecos': 'Q1028', 
    'Mauricio': 'Q1027', 
    'Mauritania': 'Q1025', 
    'México': 'Q96', 
    #'Micronesia': 'Q702', 
    'Moldavia': 'Q217', 
    'Mónaco': 'Q235', 
    'Mongolia': 'Q711', 
    'Montenegro': 'Q236', 
    'Mozambique': 'Q1029', 
    'Namibia': 'Q1030', 
    'Nauru': 'Q697', 
    'Nepal': 'Q837', 
    'Nicaragua': 'Q811', 
    'Níger': 'Q1032', 
    'Nigeria': 'Q1033', 
    'Noruega': 'Q20', 
    'Nueva Zelanda': 'Q664', 
    'Omán': 'Q842', 
    'Países Bajos': 'Q55', 
    'Pakistán': 'Q843', 
    'Palaos': 'Q695', 
    'Panamá': 'Q804', 
    'Papúa Nueva Guinea': 'Q691', 
    'Paraguay': 'Q733', 
    'Perú': 'Q419', 
    'Polonia': 'Q36', 
    'Portugal': 'Q45', 
    'Reino Unido': 'Q145', 
    'República Árabe Saharaui Democrática': 'Q40362', 
    'República Centroafricana': 'Q929', 
    'República Checa': 'Q213', 
    'República de China': 'Q865', 
    'República de Macedonia': 'Q221', 
    'República del Congo': 'Q971', 
    'República Democrática del Congo': 'Q974', 
    'República Dominicana': 'Q786', 
    'República Popular China': 'Q148', 
    'Ruanda': 'Q1037', 
    'Rumania': 'Q218', 
    'Rusia': 'Q159', 
    'Samoa': 'Q683', 
    'San Cristóbal y Nieves': 'Q763', 
    'San Marino': 'Q238', 
    'San Vicente y las Granadinas': 'Q757', 
    'Santa Lucía': 'Q760', 
    'Santo Tomé y Príncipe': 'Q1039', 
    'Senegal': 'Q1041', 
    'Serbia': 'Q403', 
    'Seychelles': 'Q1042', 
    'Sierra Leona': 'Q1044', 
    'Singapur': 'Q334', 
    'Siria': 'Q858', 
    'Somalia': 'Q1045', 
    'Sri Lanka': 'Q854', 
    'Suazilandia': 'Q1050', 
    'Sudáfrica': 'Q258', 
    'Sudán': 'Q1049', 
    'Sudán del Sur': 'Q958', 
    'Suecia': 'Q34', 
    'Suiza': 'Q39', 
    'Surinam': 'Q730', 
    'Tailandia': 'Q869', 
    'Tanzania': 'Q924', 
    'Tayikistán': 'Q863', 
    'Timor Oriental': 'Q574', 
    'Togo': 'Q945', 
    'Tonga': 'Q678', 
    'Trinidad y Tobago': 'Q754', 
    'Túnez': 'Q948', 
    'Turkmenistán': 'Q874', 
    'Turquía': 'Q43', 
    'Tuvalu': 'Q672', 
    'Ucrania': 'Q212', 
    'Uganda': 'Q1036', 
    'Uruguay': 'Q77', 
    'Uzbekistán': 'Q265', 
    'Vanuatu': 'Q686', 
    'Venezuela': 'Q717', 
    'Vietnam': 'Q881', 
    'Yemen': 'Q805', 
    'Yibuti': 'Q977', 
    'Zambia': 'Q953', 
    'Zimbabue': 'Q954', 
}

ocupaciones = {
    'abad': {'ms': 'abad', 'fs': 'abadesa', 'mp': 'abades', 'fp': 'abadesas' }, 
    'abogado': {'ms': 'abogado', 'fs': 'abogada', 'mp': 'abogados', 'fp': 'abogadas' }, 
    'abogado defensor': {'ms': 'abogado defensor', 'fs': 'abogada defensora', 'mp': 'abogados defensores', 'fp': 'abogadas defensoras' }, 
    'académico': {'ms': 'académico', 'fs': 'académica', 'mp': 'académicos', 'fp': 'académicas' }, 
    'acordeonista': {'ms': 'acordeonista', 'fs': 'acordeonista', 'mp': 'acordeonistas', 'fp': 'acordeonistas' }, 
    'activista': {'ms': 'activista', 'fs': 'activista', 'mp': 'activistas', 'fp': 'activistas' }, 
    'actor': {'ms': 'actor', 'fs': 'actriz', 'mp': 'actores', 'fp': 'actrices' }, 
    'actor de cine': {'ms': 'actor de cine', 'fs': 'actriz de cine', 'mp': 'actores de cine', 'fp': 'actrices de cine' }, 
    'actor de doblaje': {'ms': 'actor de doblaje', 'fs': 'actriz de doblaje', 'mp': 'actores de doblaje', 'fp': 'actrices de doblaje' }, 
    'actor de teatro': {'ms': 'actor de teatro', 'fs': 'actriz de teatro', 'mp': 'actores de teatro', 'fp': 'actrices de teatro' }, 
    'actor de teatro musical': {'ms': 'actor de teatro musical', 'fs': 'actriz de teatro musical', 'mp': 'actores de teatro musical', 'fp': 'actrices de teatro musical' }, 
    'actor de televisión': {'ms': 'actor de televisión', 'fs': 'actriz de televisión', 'mp': 'actores de televisión', 'fp': 'actrices de televisión' }, 
    'actor de voz': {'ms': 'actor de voz', 'fs': 'actriz de voz', 'mp': 'actores de voz', 'fp': 'actrices de voz' }, 
    'actor pornográfico': {'ms': 'actor pornográfico', 'fs': 'actriz pornográfica', 'mp': 'actores pornográficos', 'fp': 'actrices pornográficas' },
    'acuarelista': {'ms': 'acuarelista', 'fs': 'acuarelista', 'mp': 'acuarelistas', 'fp': 'acuarelistas' }, 
    'aeronauta': {'ms': 'aeronauta', 'fs': 'aeronauta', 'mp': 'aeronautas', 'fp': 'aeronautas' }, 
    'agente de bolsa': {'ms': 'agente de bolsa', 'fs': 'agente de bolsa', 'mp': 'agentes de bolsa', 'fp': 'agentes de bolsa' }, 
    'agente de talentos': {'ms': 'agente de talentos', 'fs': 'agente de talentos', 'mp': 'agentes de talentos', 'fp': 'agentes de talentos' }, 
    'agente doble': {'ms': 'agente doble', 'fs': 'agente doble', 'mp': 'agentes dobles', 'fp': 'agentes dobles' }, 
    'agente penitenciario': {'ms': 'agente penitenciario', 'fs': 'agente penitenciaria', 'mp': 'agentes penitenciarios', 'fp': 'agentes penitenciarias' }, 
    'agricultor': {'ms': 'agricultor', 'fs': 'agricultora', 'mp': 'agricultores', 'fp': 'agricultoras' }, 
    'agrónomo': {'ms': 'agrónomo', 'fs': 'agrónoma', 'mp': 'agrónomos', 'fp': 'agrónomas' }, 
    'ajedrecista': {'ms': 'ajedrecista', 'fs': 'ajedrecista', 'mp': 'ajedrecistas', 'fp': 'ajedrecistas' }, 
    'alto cargo': {'ms': 'alto cargo', 'fs': 'alto cargo', 'mp': 'altos cargos', 'fp': 'altos cargos' }, 
    'algorista': {'ms': 'algorista', 'fs': 'algorista', 'mp': 'algoristas', 'fp': 'algoristas' }, 
    'amo de casa': {'ms': 'amo de casa', 'fs': 'ama de casa', 'mp': 'amos de casa', 'fp': 'amas de casa' }, 
    'amo de llaves': {'ms': 'amo de llaves', 'fs': 'ama de llaves', 'mp': 'amos de llaves', 'fp': 'amas de llaves' }, 
    'ambientalista': {'ms': 'ambientalista', 'fs': 'ambientalista', 'mp': 'ambientalistas', 'fp': 'ambientalistas' }, 
    'anarquista': {'ms': 'anarquista', 'fs': 'anarquista', 'mp': 'anarquistas', 'fp': 'anarquistas' }, 
    'anatomista': {'ms': 'anatomista', 'fs': 'anatomista', 'mp': 'anatomistas', 'fp': 'anatomistas' }, 
    'anticuario': {'ms': 'anticuario', 'fs': 'anticuaria', 'mp': 'anticuarios', 'fp': 'anticuarias' }, 
    'antropólogo': {'ms': 'antropólogo', 'fs': 'antropóloga', 'mp': 'antropólogos', 'fp': 'antropólogas' }, 
    'apneísta': {'ms': 'apneísta', 'fs': 'apneísta', 'mp': 'apneístas', 'fp': 'apneístas' }, 
    'árbitro': {'ms': 'árbitro', 'fs': 'árbitra', 'mp': 'árbitros', 'fp': 'árbitras' }, 
    'árbitro de fútbol': {'ms': 'árbitro de fútbol', 'fs': 'árbitra de fútbol', 'mp': 'árbitros de fútbol', 'fp': 'árbitras de fútbol' }, 
    'archivero': {'ms': 'archivero', 'fs': 'archivera', 'mp': 'archiveros', 'fp': 'archiveras' }, 
    'archivista paleógrafo': {'ms': 'archivista paleógrafo', 'fs': 'archivista paleógrafa', 'mp': 'archivistas paleógrafos', 'fp': 'archivistas paleógrafas' }, 
    'aristócrata': {'ms': 'aristócrata', 'fs': 'aristócrata', 'mp': 'aristócratas', 'fp': 'aristócratas' }, 
    'arpista': {'ms': 'arpista', 'fs': 'arpista', 'mp': 'arpistas', 'fp': 'arpistas' }, 
    'arqueólogo': {'ms': 'arqueólogo', 'fs': 'arqueóloga', 'mp': 'arqueólogos', 'fp': 'arqueólogas' }, 
    'arqueólogo clásico': {'ms': 'arqueólogo clásico', 'fs': 'arqueóloga clásica', 'mp': 'arqueólogos clásicos', 'fp': 'arqueólogas clásicas' }, 
    'arquero': {'ms': 'arquero', 'fs': 'arquera', 'mp': 'arqueros', 'fp': 'arqueras' }, 
    'arquitecto': {'ms': 'arquitecto', 'fs': 'arquitecta', 'mp': 'arquitectos', 'fp': 'arquitectas' }, 
    'arreglista': {'ms': 'arreglista', 'fs': 'arreglista', 'mp': 'arreglistas', 'fp': 'arreglistas' }, 
    'artesano': {'ms': 'artesano', 'fs': 'artesana', 'mp': 'artesanos', 'fp': 'artesanas' }, 
    'artista': {'ms': 'artista', 'fs': 'artista', 'mp': 'artistas', 'fp': 'artistas' }, 
    'artista callejero': {'ms': 'artista callejero', 'fs': 'artista callejero', 'mp': 'artistas callejeros', 'fp': 'artistas callejeros' }, 
    'artista contemporáneo': {'ms': 'artista contemporáneo', 'fs': 'artista contemporánea', 'mp': 'artistas contemporáneos', 'fp': 'artistas contemporáneas' }, 
    'artista de circo': {'ms': 'artista de circo', 'fs': 'artista de circo', 'mp': 'artistas de circo', 'fp': 'artistas de circo' }, 
    'artista de graffiti': {'ms': 'artista de graffiti', 'fs': 'artista de graffiti', 'mp': 'artistas de graffiti', 'fp': 'artistas de graffiti' }, 
    'artista de performance': {'ms': 'artista de performance', 'fs': 'artista de performance', 'mp': 'artistas de performance', 'fp': 'artistas de performance' }, 
    'artista digital': {'ms': 'artista digital', 'fs': 'artista digital', 'mp': 'artistas digitales', 'fp': 'artistas digitales' }, 
    'artista marcial': {'ms': 'artista marcial', 'fs': 'artista marcial', 'mp': 'artistas marciales', 'fp': 'artistas marciales' }, 
    'artista musical': {'ms': 'artista musical', 'fs': 'artista musical', 'mp': 'artistas musicales', 'fp': 'artistas musicales' }, 
    'artista plástico': {'ms': 'artista plástico', 'fs': 'artista plástica', 'mp': 'artistas plásticos', 'fp': 'artistas plásticas' }, 
    'artista textil': {'ms': 'artista textil', 'fs': 'artista textil', 'mp': 'artistas textiles', 'fp': 'artistas textiles' }, 
    'asesino en serie': {'ms': 'asesino en serie', 'fs': 'asesina en serie', 'mp': 'asesinos en serie', 'fp': 'asesinas en serie' }, 
    'asesor': {'ms': 'asesor', 'fs': 'asesora', 'mp': 'asesores', 'fp': 'asesoras' }, 
    'asesor fiscal': {'ms': 'asesor fiscal', 'fs': 'asesora fiscal', 'mp': 'asesores fiscales', 'fp': 'asesoras fiscales' }, 
    'asistente social': {'ms': 'asistente social', 'fs': 'asistenta social', 'mp': 'asistentes sociales', 'fp': 'asistentas sociales' }, 
    'astrofísico': {'ms': 'astrofísico', 'fs': 'astrofísica', 'mp': 'astrofísicos', 'fp': 'astrofísicas' }, 
    'astrólogo': {'ms': 'astrólogo', 'fs': 'astróloga', 'mp': 'astrólogos', 'fp': 'astrólogas' }, 
    'astrónomo': {'ms': 'astrónomo', 'fs': 'astrónoma', 'mp': 'astrónomos', 'fp': 'astrónomas' }, 
    'atleta': {'ms': 'atleta', 'fs': 'atleta', 'mp': 'atletas', 'fp': 'atletas' }, 
    'autobiógrafo': {'ms': 'autobiógrafo', 'fs': 'autobiógrafa', 'mp': 'autobiógrafos', 'fp': 'autobiógrafas' }, 
    'autor': {'ms': 'autor', 'fs': 'autora', 'mp': 'autores', 'fp': 'autoras' }, 
    'aventurero': {'ms': 'aventurero', 'fs': 'aventurera', 'mp': 'aventureros', 'fp': 'aventureras' }, 
    'aviador': {'ms': 'aviador', 'fs': 'aviadora', 'mp': 'aviadores', 'fp': 'aviadoras' }, 
    'bacteriólogo': {'ms': 'bacteriólogo', 'fs': 'bacterióloga', 'mp': 'bacteriólogos', 'fp': 'bacteriólogas' }, 
    'badmintonista': {'ms': 'badmintonista', 'fs': 'badmintonista', 'mp': 'badmintonistas', 'fp': 'badmintonistas' }, 
    'bailarín': {'ms': 'bailarín', 'fs': 'bailarina', 'mp': 'bailarines', 'fp': 'bailarinas' }, 
    'bailarín de ballet': {'ms': 'bailarín de ballet', 'fs': 'bailarina de ballet', 'mp': 'bailarines de ballet', 'fp': 'bailarinas de ballet' }, 
    'baloncestista': {'ms': 'baloncestista', 'fs': 'baloncestista', 'mp': 'baloncestistas', 'fp': 'baloncestistas' }, 
    'balonmanista': {'ms': 'balonmanista', 'fs': 'balonmanista', 'mp': 'balonmanistas', 'fp': 'balonmanistas' }, 
    'banjista': {'ms': 'banjista', 'fs': 'banjista', 'mp': 'banjistas', 'fp': 'banjistas' }, 
    'banquero': {'ms': 'banquero', 'fs': 'banquera', 'mp': 'banqueros', 'fp': 'banqueras' }, 
    'baterista': {'ms': 'baterista', 'fs': 'baterista', 'mp': 'bateristas', 'fp': 'bateristas' }, 
    'bhikkhuni': {'ms': 'bhikkhuni', 'fs': 'bhikkhuni', 'mp': 'bhikkhunis', 'fp': 'bhikkhunis' }, 
    'biatleta': {'ms': 'biatleta', 'fs': 'biatleta', 'mp': 'biatletas', 'fp': 'biatletas' }, 
    'bibliotecario': {'ms': 'bibliotecario', 'fs': 'bibliotecaria', 'mp': 'bibliotecarios', 'fp': 'bibliotecarias' }, 
    'biógrafo': {'ms': 'biógrafo', 'fs': 'biógrafa', 'mp': 'biógrafos', 'fp': 'biógrafas' }, 
    'biólogo': {'ms': 'biólogo', 'fs': 'bióloga', 'mp': 'biólogos', 'fp': 'biólogas' }, 
    'biólogo molecular': {'ms': 'biólogo molecular', 'fs': 'bióloga molecular', 'mp': 'biólogos moleculares', 'fp': 'biólogas moleculares' }, 
    'bioquímico': {'ms': 'bioquímico', 'fs': 'bioquímica', 'mp': 'bioquímicos', 'fp': 'bioquímicas' }, 
    'bloguero': {'ms': 'bloguero', 'fs': 'bloguera', 'mp': 'blogueros', 'fp': 'blogueras' }, 
    'botánico': {'ms': 'botánico', 'fs': 'botánica', 'mp': 'botánicos', 'fp': 'botánicas' }, 
    'boxeador': {'ms': 'boxeador', 'fs': 'boxeadora', 'mp': 'boxeadores', 'fp': 'boxeadoras' }, 
    'cabaretista': {'ms': 'cabaretista', 'fs': 'cabaretista', 'mp': 'cabaretistas', 'fp': 'cabaretistas' }, 
    'camarógrafo': {'ms': 'camarógrafo', 'fs': 'camarógrafa', 'mp': 'camarógrafos', 'fp': 'camarógrafas' }, 
    'cantante': {'ms': 'cantante', 'fs': 'cantante', 'mp': 'cantantes', 'fp': 'cantantes' }, 
    'cantante de ópera': {'ms': 'cantante de ópera', 'fs': 'cantante de ópera', 'mp': 'cantantes de ópera', 'fp': 'cantantes de ópera' }, 
    'cantautor': {'ms': 'cantautor', 'fs': 'cantautora', 'mp': 'cantautores', 'fp': 'cantautoras' }, 
    'cardiólogo': {'ms': 'cardiólogo', 'fs': 'cardióloga', 'mp': 'cardiólogos', 'fp': 'cardiólogas' }, 
    'caricaturista': {'ms': 'caricaturista', 'fs': 'caricaturista', 'mp': 'caricaturistas', 'fp': 'caricaturistas' }, 
    'cartelista': {'ms': 'cartelista', 'fs': 'cartelista', 'mp': 'cartelistas', 'fp': 'cartelistas' }, 
    'catedrático': {'ms': 'catedrático', 'fs': 'catedrática', 'mp': 'catedráticos', 'fp': 'catedráticas' }, 
    'ceramista': {'ms': 'ceramista', 'fs': 'ceramista', 'mp': 'ceramistas', 'fp': 'ceramistas' }, 
    'chef': {'ms': 'chef', 'fs': 'chef', 'mp': 'chefs', 'fp': 'chefs' }, 
    'ciberactivista': {'ms': 'ciberactivista', 'fs': 'ciberactivista', 'mp': 'ciberactivistas', 'fp': 'ciberactivistas' }, 
    'científico': {'ms': 'científico', 'fs': 'científica', 'mp': 'científicos', 'fp': 'científicas' }, 
    'científico de la literatura': {'ms': 'científico de la literatura', 'fs': 'científica de la literatura', 'mp': 'científicos de la literatura', 'fp': 'científicas de la literatura' }, 
    'ciclista': {'ms': 'ciclista', 'fs': 'ciclista', 'mp': 'ciclistas', 'fp': 'ciclistas' }, 
    'ciclista de ciclocrós': {'ms': 'ciclista de ciclocrós', 'fs': 'ciclista de ciclocrós', 'mp': 'ciclistas de ciclocrós', 'fp': 'ciclistas de ciclocrós' }, 
    'ciclista de pista': {'ms': 'ciclista de pista', 'fs': 'ciclista de pista', 'mp': 'ciclistas de pista', 'fp': 'ciclistas de pista' }, 
    'cirujano': {'ms': 'cirujano', 'fs': 'cirujana', 'mp': 'cirujanos', 'fp': 'cirujanas' }, 
    'clarinetista': {'ms': 'clarinetista', 'fs': 'clarinetista', 'mp': 'clarinetistas', 'fp': 'clarinetistas' }, 
    'clavecinista': {'ms': 'clavecinista', 'fs': 'clavecinista', 'mp': 'clavecinistas', 'fp': 'clavecinistas' }, 
    'cocinero': {'ms': 'cocinero', 'fs': 'cocinera', 'mp': 'cocineros', 'fp': 'cocineras' }, 
    'coleccionista': {'ms': 'coleccionista', 'fs': 'coleccionista', 'mp': 'coleccionistas', 'fp': 'coleccionistas' }, 
    'coleccionista de arte': {'ms': 'coleccionista de arte', 'fs': 'coleccionista de arte', 'mp': 'coleccionistas de arte', 'fp': 'coleccionistas de arte' }, 
    'colorista': {'ms': 'colorista', 'fs': 'colorista', 'mp': 'coloristas', 'fp': 'coloristas' }, 
    'columnista': {'ms': 'columnista', 'fs': 'columnista', 'mp': 'columnistas', 'fp': 'columnistas' }, 
    'comediante': {'ms': 'comediante', 'fs': 'comedianta', 'mp': 'comediantes', 'fp': 'comediantas' }, 
    'comediante en vivo': {'ms': 'comediante en vivo', 'fs': 'comediante en vivo', 'mp': 'comediantes en vivo', 'fp': 'comediantes en vivo' }, 
    'comentarista': {'ms': 'comentarista', 'fs': 'comentarista', 'mp': 'comentaristas', 'fp': 'comentaristas' }, 
    'comentarista deportivo': {'ms': 'comentarista deportivo', 'fs': 'comentarista deportiva', 'mp': 'comentaristas deportivos', 'fp': 'comentaristas deportivas' }, 
    'comerciante': {'ms': 'comerciante', 'fs': 'comerciante', 'mp': 'comerciantes', 'fp': 'comerciantes' }, 
    'comisario': {'ms': 'comisario', 'fs': 'comisaria', 'mp': 'comisarios', 'fp': 'comisarias' }, 
    'comisario político': {'ms': 'comisario político', 'fs': 'comisaria política', 'mp': 'comisarios políticos', 'fp': 'comisarias políticas' }, 
    'compilador': {'ms': 'compilador', 'fs': 'compiladora', 'mp': 'compiladores', 'fp': 'compiladoras' }, 
    'compositor': {'ms': 'compositor', 'fs': 'compositora', 'mp': 'compositores', 'fp': 'compositoras' }, 
    'compositor de canciones': {'ms': 'compositor de canciones', 'fs': 'compositora de canciones', 'mp': 'compositores de canciones', 'fp': 'compositoras de canciones' }, 
    'conductor radiofónico': {'ms': 'conductor radiofónico', 'fs': 'conductora radiofónica', 'mp': 'conductores radiofónicos', 'fp': 'conductoras radiofónicas' }, 
    'conservador del patrimonio': {'ms': 'conservador del patrimonio', 'fs': 'conservadora del patrimonio', 'mp': 'conservadores del patrimonio', 'fp': 'conservadoras del patrimonio' }, 
    'conservador de arte': {'ms': 'conservador de arte', 'fs': 'conservadora de arte', 'mp': 'conservadores de arte', 'fp': 'conservadoras de arte' }, 
    'consultor': {'ms': 'consultor', 'fs': 'consultora', 'mp': 'consultores', 'fp': 'consultoras' }, 
    'contorsionista': {'ms': 'contorsionista', 'fs': 'contorsionista', 'mp': 'contorsionistas', 'fp': 'contorsionistas' }, 
    'coreógrafo': {'ms': 'coreógrafo', 'fs': 'coreógrafa', 'mp': 'coreógrafos', 'fp': 'coreógrafas' }, 
    'corista': {'ms': 'corista', 'fs': 'corista', 'mp': 'coristas', 'fp': 'coristas' }, 
    'corredor': {'ms': 'corredor', 'fs': 'corredora', 'mp': 'corredores', 'fp': 'corredoras' }, 
    'corresponsal': {'ms': 'corresponsal', 'fs': 'corresponsal', 'mp': 'corresponsales', 'fp': 'corresponsales' }, 
    'corresponsal de guerra': {'ms': 'corresponsal de guerra', 'fs': 'corresponsal de guerra', 'mp': 'corresponsales de guerra', 'fp': 'corresponsales de guerra' }, 
    'cortesana': {'ms': 'cortesana', 'fs': 'cortesana', 'mp': 'cortesanas', 'fp': 'cortesanas' }, 
    'criminólogo': {'ms': 'criminólogo', 'fs': 'criminóloga', 'mp': 'criminólogos', 'fp': 'criminólogas' }, 
    'crítico': {'ms': 'crítico', 'fs': 'crítica', 'mp': 'críticos', 'fp': 'críticas' }, 
    'crítico de arte': {'ms': 'crítico de arte', 'fs': 'crítica de arte', 'mp': 'críticos de arte', 'fp': 'críticas de arte' }, 
    'crítico de cine': {'ms': 'crítico de cine', 'fs': 'crítica de cine', 'mp': 'críticos de cine', 'fp': 'críticas de cine' }, 
    'crítico de teatro': {'ms': 'crítico de teatro', 'fs': 'crítica de teatro', 'mp': 'críticos de teatro', 'fp': 'críticas de teatro' }, 
    'crítico literario': {'ms': 'crítico literario', 'fs': 'crítica literaria', 'mp': 'críticos literarios', 'fp': 'críticas literarias' }, 
    'cuentista': {'ms': 'cuentista', 'fs': 'cuentista', 'mp': 'cuentistas', 'fp': 'cuentistas' }, 
    'curler': {'ms': 'curler', 'fs': 'curler', 'mp': 'curlers', 'fp': 'curlers' }, 
    'dama de compañía': {'ms': 'dama de compañía', 'fs': 'dama de compañía', 'mp': 'damas de compañía', 'fp': 'damas de compañía' }, 
    'delineante': {'ms': 'delineante', 'fs': 'delineante', 'mp': 'delineantes', 'fp': 'delineantes' }, 
    'demógrafo': {'ms': 'demógrafo', 'fs': 'demógrafa', 'mp': 'demógrafos', 'fp': 'demógrafas' }, 
    'dentista': {'ms': 'dentista', 'fs': 'dentista', 'mp': 'dentistas', 'fp': 'dentistas' }, 
    'deportista': {'ms': 'deportista', 'fs': 'deportista', 'mp': 'deportistas', 'fp': 'deportistas' }, 
    'desarrollador de videojuegos': {'ms': 'desarrollador de videojuegos', 'fs': 'desarrolladora de videojuegos', 'mp': 'desarrolladores de videojuegos', 'fp': 'desarrolladoras de videojuegos' }, 
    'diaconisa': {'ms': 'diaconisa', 'fs': 'diaconisa', 'mp': 'diaconisas', 'fp': 'diaconisas' }, 
    'diarista': {'ms': 'diarista', 'fs': 'diarista', 'mp': 'diaristas', 'fp': 'diaristas' }, 
    'diplomático': {'ms': 'diplomático', 'fs': 'diplomática', 'mp': 'diplomáticos', 'fp': 'diplomáticas' }, 
    'dibujante': {'ms': 'dibujante', 'fs': 'dibujante', 'mp': 'dibujantes', 'fp': 'dibujantes' }, 
    'dibujante arquitectónico': {'ms': 'dibujante arquitectónico', 'fs': 'dibujante arquitectónica', 'mp': 'dibujantes arquitectónicos', 'fp': 'dibujantes arquitectónicas' }, 
    'dibujante de historieta': {'ms': 'dibujante de historieta', 'fs': 'dibujante de historieta', 'mp': 'dibujantes de historietas', 'fp': 'dibujantes de historietas' }, 
    'dibujante de prensa': {'ms': 'dibujante de prensa', 'fs': 'dibujante de prensa', 'mp': 'dibujantes de prensa', 'fp': 'dibujantes de prensa' }, 
    'director artístico': {'ms': 'director artístico', 'fs': 'directora artística', 'mp': 'directores artísticos', 'fp': 'directoras artísticas' }, 
    'director de casting': {'ms': 'director de casting', 'fs': 'directora de casting', 'mp': 'directores de casting', 'fp': 'directoras de casting' }, 
    'director de cine': {'ms': 'director de cine', 'fs': 'directora de cine', 'mp': 'directores de cine', 'fp': 'directoras de cine' }, 
    'director de colección': {'ms': 'director de colección', 'fs': 'directora de colección', 'mp': 'directores de colección', 'fp': 'directoras de colección' }, 
    'director de coro': {'ms': 'director de coro', 'fs': 'directora de coro', 'mp': 'directores de coro', 'fp': 'directoras de coro' }, 
    'director de documentales': {'ms': 'director de documentales', 'fs': 'directora de documentales', 'mp': 'directores de documentales', 'fp': 'directoras de documentales' }, 
    'director de estudios': {'ms': 'director de estudios', 'fs': 'directora de estudios', 'mp': 'directores de estudios', 'fp': 'directoras de estudios' }, 
    'director de finanzas': {'ms': 'director de finanzas', 'fs': 'directora de finanzas', 'mp': 'directores de finanzas', 'fp': 'directoras de finanzas' }, 
    'director de fotografía': {'ms': 'director de fotografía', 'fs': 'directora de fotografía', 'mp': 'directores de fotografía', 'fp': 'directoras de fotografía' }, 
    'director de teatro': {'ms': 'director de teatro', 'fs': 'directora de teatro', 'mp': 'directores de teatro', 'fp': 'directoras de teatro' }, 
    'director de televisión': {'ms': 'director de televisión', 'fs': 'directora de televisión', 'mp': 'directores de televisión', 'fp': 'directoras de televisión' }, 
    'director de orquesta': {'ms': 'director de orquesta', 'fs': 'directora de orquesta', 'mp': 'directores de orquesta', 'fp': 'directoras de orquesta' }, 
    'director de videos musicales': {'ms': 'director de videos musicales', 'fs': 'directora de videos musicales', 'mp': 'directores de videos musicales', 'fp': 'directoras de videos musicales' }, 
    'director deportivo': {'ms': 'director deportivo', 'fs': 'directora deportiva', 'mp': 'directores deportivos', 'fp': 'directoras deportivas' }, 
    'director ejecutivo': {'ms': 'director ejecutivo', 'fs': 'directora ejecutiva', 'mp': 'directores ejecutivos', 'fp': 'directoras ejecutivas' }, 
    'director musical': {'ms': 'director musical', 'fs': 'directora musical', 'mp': 'directores musicales', 'fp': 'directoras musicales' }, 
    'disc jockey': {'ms': 'disc jockey', 'fs': 'disc jockey', 'mp': 'disc jockeys', 'fp': 'disc jockeys' }, 
    'diseñador': {'ms': 'diseñador', 'fs': 'diseñadora', 'mp': 'diseñadores', 'fp': 'diseñadoras' }, 
    'diseñador de alta costura': {'ms': 'diseñador de alta costura', 'fs': 'diseñadora de alta costura', 'mp': 'diseñadores de alta costura', 'fp': 'diseñadoras de alta costura' }, 
    'diseñador de estampillas': {'ms': 'diseñador de estampillas', 'fs': 'diseñadora de estampillas', 'mp': 'diseñadores de estampillas', 'fp': 'diseñadoras de estampillas' }, 
    'diseñador de joyas': {'ms': 'diseñador de joyas', 'fs': 'diseñadora de joyas', 'mp': 'diseñadores de joyas', 'fp': 'diseñadoras de joyas' }, 
    'diseñador de moda': {'ms': 'diseñador de moda', 'fs': 'diseñadora de moda', 'mp': 'diseñadores de moda', 'fp': 'diseñadoras de moda' }, 
    'diseñador de vestuario': {'ms': 'diseñador de vestuario', 'fs': 'diseñadora de vestuario', 'mp': 'diseñadores de vestuario', 'fp': 'diseñadoras de vestuario' }, 
    'diseñador gráfico': {'ms': 'diseñador gráfico', 'fs': 'diseñadora gráfica', 'mp': 'diseñadores gráficos', 'fp': 'diseñadoras gráficas' }, 
    'diseñador industrial': {'ms': 'diseñador industrial', 'fs': 'diseñadora industrial', 'mp': 'diseñadores industriales', 'fp': 'diseñadoras industriales' }, 
    'diseñador textil': {'ms': 'diseñador textil', 'fs': 'diseñadora textil', 'mp': 'diseñadores textiles', 'fp': 'diseñadoras textiles' }, 
    'disidente': {'ms': 'disidente', 'fs': 'disidente', 'mp': 'disidentes', 'fp': 'disidentes' }, 
    'divulgador científico': {'ms': 'divulgador científico', 'fs': 'divulgadora científica', 'mp': 'divulgadores científicos', 'fp': 'divulgadoras científicas' }, 
    'docente': {'ms': 'docente', 'fs': 'docente', 'mp': 'docentes', 'fp': 'docentes' }, 
    'documentalista': {'ms': 'documentalista', 'fs': 'documentalista', 'mp': 'documentalistas', 'fp': 'documentalistas' }, 
    'dramaturgo': {'ms': 'dramaturgo', 'fs': 'dramaturga', 'mp': 'dramaturgos', 'fp': 'dramaturgas' }, 
    'economista': {'ms': 'economista', 'fs': 'economista', 'mp': 'economistas', 'fp': 'economistas' }, 
    'editor': {'ms': 'editor', 'fs': 'editora', 'mp': 'editores', 'fp': 'editoras' }, 
    'editor colaborador': {'ms': 'editor colaborador', 'fs': 'editora colaboradora', 'mp': 'editores colaboradores', 'fp': 'editoras colaboradoras' }, 
    'editor de moda': {'ms': 'editor de moda', 'fs': 'editora de moda', 'mp': 'editores de moda', 'fp': 'editoras de moda' }, 
    'editor de periódico': {'ms': 'editor de periódico', 'fs': 'editora de periódico', 'mp': 'editores de periódico', 'fp': 'editoras de periódico' }, 
    'editor literario': {'ms': 'editor literario', 'fs': 'editora literaria', 'mp': 'editores literarios', 'fp': 'editoras literarias' }, 
    'educador': {'ms': 'educador', 'fs': 'educadora', 'mp': 'educadores', 'fp': 'educadoras' }, 
    'educador especializado': {'ms': 'educador especializado', 'fs': 'educadora especializada', 'mp': 'educadores especializados', 'fp': 'educadoras especializadas' }, 
    'educador sexual': {'ms': 'educador sexual', 'fs': 'educadora sexual', 'mp': 'educadores sexuales', 'fp': 'educadoras sexuales' }, 
    'egiptólogo': {'ms': 'egiptólogo', 'fs': 'egiptóloga', 'mp': 'egiptólogos', 'fp': 'egiptólogas' }, 
    'embajador': {'ms': 'embajador', 'fs': 'embajadora', 'mp': 'embajadores', 'fp': 'embajadoras' }, 
    'empleado': {'ms': 'empleado', 'fs': 'empleada', 'mp': 'empleados', 'fp': 'empleadas' }, 
    'emprendedor': {'ms': 'emprendedor', 'fs': 'emprendedora', 'mp': 'emprendedores', 'fp': 'emprendedoras' }, 
    'empresario': {'ms': 'empresario', 'fs': 'empresaria', 'mp': 'empresarios', 'fp': 'empresarias' }, 
    'empresario de medios': {'ms': 'empresario de medios', 'fs': 'empresaria de medios', 'mp': 'empresarios de medios', 'fp': 'empresarias de medios' }, 
    'enfermero': {'ms': 'enfermero', 'fs': 'enfermera', 'mp': 'enfermeros', 'fp': 'enfermeras' }, 
    'ensayista': {'ms': 'ensayista', 'fs': 'ensayista', 'mp': 'ensayistas', 'fp': 'ensayistas' }, 
    'entomólogo': {'ms': 'entomólogo', 'fs': 'entomóloga', 'mp': 'entomólogos', 'fp': 'entomólogas' }, 
    'entrenador': {'ms': 'entrenador', 'fs': 'entrenadora', 'mp': 'entrenadores', 'fp': 'entrenadoras' }, 
    'entrenador de baloncesto': {'ms': 'entrenador de baloncesto', 'fs': 'entrenadora de baloncesto', 'mp': 'entrenadores de baloncesto', 'fp': 'entrenadoras de baloncesto' }, 
    'entrenador de balonmano': {'ms': 'entrenador de balonmano', 'fs': 'entrenadora de balonmano', 'mp': 'entrenadores de balonmano', 'fp': 'entrenadoras de balonmano' }, 
    'entrenador de fútbol': {'ms': 'entrenador de fútbol', 'fs': 'entrenadora de fútbol', 'mp': 'entrenadores de fútbol', 'fp': 'entrenadoras de fútbol' }, 
    'entrenador de tenis': {'ms': 'entrenador de tenis', 'fs': 'entrenadora de tenis', 'mp': 'entrenadores de tenis', 'fp': 'entrenadoras de tenis' }, 
    'entrenador personal': {'ms': 'entrenador personal', 'fs': 'entrenadora personal', 'mp': 'entrenadores personales', 'fp': 'entrenadoras personales' }, 
    'epidemiólogo': {'ms': 'epidemiólogo', 'fs': 'epidemióloga', 'mp': 'epidemiólogos', 'fp': 'epidemiólogas' }, 
    'escalador en roca': {'ms': 'escalador en roca', 'fs': 'escaladora en roca', 'mp': 'escaladores en roca', 'fp': 'escaladoras en roca' }, 
    'escenógrafo': {'ms': 'escenógrafo', 'fs': 'escenógrafa', 'mp': 'escenógrafos', 'fp': 'escenógrafas' }, 
    'escritor': {'ms': 'escritor', 'fs': 'escritora', 'mp': 'escritores', 'fp': 'escritoras' }, 
    'escritor de ciencia ficción': {'ms': 'escritor de ciencia ficción', 'fs': 'escritora de ciencia ficción', 'mp': 'escritores de ciencia ficción', 'fp': 'escritoras de ciencia ficción' }, 
    'escritor de género policiaco': {'ms': 'escritor de género policiaco', 'fs': 'escritora de género policiaco', 'mp': 'escritores de género policiaco', 'fp': 'escritoras de género policiaco' }, 
    'escritor de literatura infantil': {'ms': 'escritor de literatura infantil', 'fs': 'escritora de literatura infantil', 'mp': 'escritores de literatura infantil', 'fp': 'escritoras de literatura infantil' }, 
    'escritor de no ficción': {'ms': 'escritor de no ficción', 'fs': 'escritora de no ficción', 'mp': 'escritores de no ficción', 'fp': 'escritoras de no ficción' }, 
    'escritor sobre medicina': {'ms': 'escritor sobre medicina', 'fs': 'escritora sobre medicina', 'mp': 'escritores sobre medicina', 'fp': 'escritoras sobre medicina' }, 
    'escultor': {'ms': 'escultor', 'fs': 'escultora', 'mp': 'escultores', 'fp': 'escultoras' }, 
    'esgrimista': {'ms': 'esgrimista', 'fs': 'esgrimista', 'mp': 'esgrimistas', 'fp': 'esgrimistas' }, 
    'eslavista': {'ms': 'eslavista', 'fs': 'eslavista', 'mp': 'eslavistas', 'fp': 'eslavistas' }, 
    'especialista de cine': {'ms': 'especialista de cine', 'fs': 'especialista de cine', 'mp': 'especialistas de cine', 'fp': 'especialistas de cine' }, 
    'espeleólogo': {'ms': 'espeleólogo', 'fs': 'espeleóloga', 'mp': 'espeleólogos', 'fp': 'espeleólogas' }, 
    'esperantista': {'ms': 'esperantista', 'fs': 'esperantista', 'mp': 'esperantistas', 'fp': 'esperantistas' }, 
    'esquiador': {'ms': 'esquiador', 'fs': 'esquiadora', 'mp': 'esquiadores', 'fp': 'esquiadoras' }, 
    'esquiador acrobático': {'ms': 'esquiador acrobático', 'fs': 'esquiadora acrobática', 'mp': 'esquiadores acrobáticos', 'fp': 'esquiadoras acrobáticas' }, 
    'esquiador alpino': {'ms': 'esquiador alpino', 'fs': 'esquiadora alpina', 'mp': 'esquiadores alpinos', 'fp': 'esquiadoras alpinas' }, 
    'esquiador de fondo': {'ms': 'esquiador de fondo', 'fs': 'esquiadora de fondo', 'mp': 'esquiadores de fondo', 'fp': 'esquiadoras de fondo' }, 
    'esquiador de travesía': {'ms': 'esquiador de travesía', 'fs': 'esquiadora de travesía', 'mp': 'esquiadores de travesía', 'fp': 'esquiadoras de travesía' }, 
    'esquiador orientador': {'ms': 'esquiador orientador', 'fs': 'esquiadora orientadora', 'mp': 'esquiadores orientadores', 'fp': 'esquiadoras orientadoras' }, 
    'estadista': {'ms': 'estadista', 'fs': 'estadista', 'mp': 'estadistas', 'fp': 'estadistas' }, 
    'estadístico': {'ms': 'estadístico', 'fs': 'estadística', 'mp': 'estadísticos', 'fp': 'estadísticas' }, 
    'etnógrafo': {'ms': 'etnógrafo', 'fs': 'etnógrafa', 'mp': 'etnógrafos', 'fp': 'etnógrafas' }, 
    'etnólogo': {'ms': 'etnólogo', 'fs': 'etnóloga', 'mp': 'etnólogos', 'fp': 'etnólogas' }, 
    'etnomusicólogo': {'ms': 'etnomusicólogo', 'fs': 'etnomusicóloga', 'mp': 'etnomusicólogos', 'fp': 'etnomusicólogas' }, 
    'explorador': {'ms': 'explorador', 'fs': 'exploradora', 'mp': 'exploradores', 'fp': 'exploradoras' }, 
    'fabricante de pianos': {'ms': 'fabricante de pianos', 'fs': 'fabricante de pianos', 'mp': 'fabricantes de pianos', 'fp': 'fabricantes de pianos' }, 
    'feminista': {'ms': 'feminista', 'fs': 'feminista', 'mp': 'feministas', 'fp': 'feministas' }, 
    'filántropo': {'ms': 'filántropo', 'fs': 'filántropa', 'mp': 'filántropos', 'fp': 'filántropas' }, 
    'filólogo': {'ms': 'filólogo', 'fs': 'filóloga', 'mp': 'filólogos', 'fp': 'filólogas' }, 
    'filósofo': {'ms': 'filósofo', 'fs': 'filósofa', 'mp': 'filósofos', 'fp': 'filósofas' }, 
    'filólogo clásico': {'ms': 'filólogo clásico', 'fs': 'filóloga clásica', 'mp': 'filólogos clásicos', 'fp': 'filólogas clásicas' }, 
    'financiero': {'ms': 'financiero', 'fs': 'financiera', 'mp': 'financieros', 'fp': 'financieras' }, 
    'físico': {'ms': 'físico', 'fs': 'física', 'mp': 'físicos', 'fp': 'físicas' }, 
    'flautista': {'ms': 'flautista', 'fs': 'flautista', 'mp': 'flautistas', 'fp': 'flautistas' }, 
    'folclorista': {'ms': 'folclorista', 'fs': 'folclorista', 'mp': 'folcloristas', 'fp': 'folcloristas' }, 
    'fondista': {'ms': 'fondista', 'fs': 'fondista', 'mp': 'fondistas', 'fp': 'fondistas' }, 
    'fotógrafo': {'ms': 'fotógrafo', 'fs': 'fotógrafa', 'mp': 'fotógrafos', 'fp': 'fotógrafas' }, 
    'fotógrafo de escena': {'ms': 'fotógrafo de escena', 'fs': 'fotógrafa de escena', 'mp': 'fotógrafos de escena', 'fp': 'fotógrafas de escena' }, 
    'fotomodelo': {'ms': 'fotomodelo', 'fs': 'fotomodelo', 'mp': 'fotomodelos', 'fp': 'fotomodelos' }, 
    'fotoperiodista': {'ms': 'fotoperiodista', 'fs': 'fotoperiodista', 'mp': 'fotoperiodistas', 'fp': 'fotoperiodistas' }, 
    'funcionario': {'ms': 'funcionario', 'fs': 'funcionaria', 'mp': 'funcionarios', 'fp': 'funcionarias' }, 
    'futbolista': {'ms': 'futbolista', 'fs': 'futbolista', 'mp': 'futbolistas', 'fp': 'futbolistas' }, 
    'ganadero': {'ms': 'ganadero', 'fs': 'ganadera', 'mp': 'ganaderos', 'fp': 'ganaderas' }, 
    'geisha': {'ms': 'geisha', 'fs': 'geisha', 'mp': 'geishas', 'fp': 'geishas' }, 
    'genetista': {'ms': 'genetista', 'fs': 'genetista', 'mp': 'genetistas', 'fp': 'genetistas' }, 
    'geólogo': {'ms': 'geólogo', 'fs': 'geóloga', 'mp': 'geólogos', 'fp': 'geólogas' }, 
    'germanista': {'ms': 'germanista', 'fs': 'germanista', 'mp': 'germanistas', 'fp': 'germanistas' }, 
    'gimnasta': {'ms': 'gimnasta', 'fs': 'gimnasta', 'mp': 'gimnastas', 'fp': 'gimnastas' }, 
    'gimnasta artístico': {'ms': 'gimnasta artístico', 'fs': 'gimnasta artística', 'mp': 'gimnastas artísticos', 'fp': 'gimnastas artísticas' }, 
    'gimnasta rítmico': {'ms': 'gimnasta rítmico', 'fs': 'gimnasta rítmica', 'mp': 'gimnastas rítmicos', 'fp': 'gimnastas rítmicas' }, 
    'ginecólogo': {'ms': 'ginecólogo', 'fs': 'ginecóloga', 'mp': 'ginecólogos', 'fp': 'ginecólogas' }, 
    'glaciólogo': {'ms': 'glaciólogo', 'fs': 'glacióloga', 'mp': 'glaciólogos', 'fp': 'glaciólogas' }, 
    'golfista': {'ms': 'golfista', 'fs': 'golfista', 'mp': 'golfistas', 'fp': 'golfistas' }, 
    'grabador': {'ms': 'grabador', 'fs': 'grabadora', 'mp': 'grabadores', 'fp': 'grabadoras' }, 
    'grabador de cobre': {'ms': 'grabador de cobre', 'fs': 'grabadora de cobre', 'mp': 'grabadores de cobre', 'fp': 'grabadoras de cobre' }, 
    'gramático': {'ms': 'gramático', 'fs': 'gramática', 'mp': 'gramáticos', 'fp': 'gramáticas' }, 
    'guardabosques': {'ms': 'guardabosques', 'fs': 'guardabosques', 'mp': 'guardabosques', 'fp': 'guardabosques' }, 
    'guía de montaña': {'ms': 'guía de montaña', 'fs': 'guía de montaña', 'mp': 'guías de montaña', 'fp': 'guías de montaña' }, 
    'guionista': {'ms': 'guionista', 'fs': 'guionista', 'mp': 'guionistas', 'fp': 'guionistas' }, 
    'guionista de historieta': {'ms': 'guionista de historieta', 'fs': 'guionista de historieta', 'mp': 'guionistas de historieta', 'fp': 'guionistas de historieta' }, 
    'guitarrista': {'ms': 'guitarrista', 'fs': 'guitarrista', 'mp': 'guitarristas', 'fp': 'guitarristas' }, 
    'guitarrista clásico': {'ms': 'guitarrista clásico', 'fs': 'guitarrista clásica', 'mp': 'guitarristas clásicos', 'fp': 'guitarristas clásicas' }, 
    'guitarrista de jazz': {'ms': 'guitarrista de jazz', 'fs': 'guitarrista de jazz', 'mp': 'guitarristas de jazz', 'fp': 'guitarristas de jazz' }, 
    'hematólogo': {'ms': 'hematólogo', 'fs': 'hematóloga', 'mp': 'hematólogos', 'fp': 'hematólogas' }, 
    'halterófilo': {'ms': 'halterófilo', 'fs': 'halterófila', 'mp': 'halterófilos', 'fp': 'halterófilas' }, 
    'historiador': {'ms': 'historiador', 'fs': 'historiadora', 'mp': 'historiadores', 'fp': 'historiadoras' }, 
    'historiador de la Edad Moderna': {'ms': 'historiador de la Edad Moderna', 'fs': 'historiadora de la Edad Moderna', 'mp': 'historiadores de la Edad Moderna', 'fp': 'historiadoras de la Edad Moderna' }, 
    'historiador de la literatura': {'ms': 'historiador de la literatura', 'fs': 'historiadora de la literatura', 'mp': 'historiadores de la literatura', 'fp': 'historiadoras de la literatura' }, 
    'historiador de la matemática': {'ms': 'historiador de la matemática', 'fs': 'historiadora de la matemática', 'mp': 'historiadores de la matemática', 'fp': 'historiadoras de la matemática' }, 
    'historiador de la música': {'ms': 'historiador de la música', 'fs': 'historiadora de la música', 'mp': 'historiadores de la música', 'fp': 'historiadoras de la música' }, 
    'historiador de la religión': {'ms': 'historiador de la religión', 'fs': 'historiadora de la religión', 'mp': 'historiadores de la religión', 'fp': 'historiadoras de la religión' }, 
    'historiador del arte': {'ms': 'historiador del arte', 'fs': 'historiadora del arte', 'mp': 'historiadores del arte', 'fp': 'historiadoras del arte' }, 
    'historiador del derecho': {'ms': 'historiador del derecho', 'fs': 'historiadora del derecho', 'mp': 'historiadores del derecho', 'fp': 'historiadoras del derecho' }, 
    'historiador local': {'ms': 'historiador local', 'fs': 'historiadora local', 'mp': 'historiadores locales', 'fp': 'historiadoras locales' }, 
    'historiador social': {'ms': 'historiador social', 'fs': 'historiadora social', 'mp': 'historiadores sociales', 'fp': 'historiadoras sociales' }, 
    'historietista': {'ms': 'historietista', 'fs': 'historietista', 'mp': 'historietistas', 'fp': 'historietistas' }, 
    'humorista': {'ms': 'humorista', 'fs': 'humorista', 'mp': 'humoristas', 'fp': 'humoristas' }, 
    'humorista gráfico': {'ms': 'humorista gráfico', 'fs': 'humorista gráfica', 'mp': 'humoristas gráficos', 'fp': 'humoristas gráficas' }, 
    'iconógrafo': {'ms': 'iconógrafo', 'fs': 'iconógrafa', 'mp': 'iconógrafos', 'fp': 'iconógrafas' }, 
    'ilustrador': {'ms': 'ilustrador', 'fs': 'ilustradora', 'mp': 'ilustradores', 'fp': 'ilustradoras' }, 
    'ilustrador botánico': {'ms': 'ilustrador botánico', 'fs': 'ilustradora botánica', 'mp': 'ilustradores botánicos', 'fp': 'ilustradoras botánicas' }, 
    'impresor': {'ms': 'impresor', 'fs': 'impresora', 'mp': 'impresores', 'fp': 'impresoras' }, 
    'industrial': {'ms': 'industrial', 'fs': 'industrial', 'mp': 'industriales', 'fp': 'industriales' }, 
    'informático teórico': {'ms': 'informático teórico', 'fs': 'informática teórica', 'mp': 'informáticos teóricos', 'fp': 'informáticas teóricas' }, 
    'ingeniero': {'ms': 'ingeniero', 'fs': 'ingeniera', 'mp': 'ingenieros', 'fp': 'ingenieras' }, 
    'ingeniero aeroespacial': {'ms': 'ingeniero aeroespacial', 'fs': 'ingeniera aeroespacial', 'mp': 'ingenieros aeroespaciales', 'fp': 'ingenieras aeroespaciales' }, 
    'ingeniero civil': {'ms': 'ingeniero civil', 'fs': 'ingeniera civil', 'mp': 'ingenieros civiles', 'fp': 'ingenieras civiles' }, 
    'ingeniero de software': {'ms': 'ingeniero de software', 'fs': 'ingeniera de software', 'mp': 'ingenieros de software', 'fp': 'ingenieras de software' }, 
    'ingeniero de sonido': {'ms': 'ingeniero de sonido', 'fs': 'ingeniera de sonido', 'mp': 'ingenieros de sonido', 'fp': 'ingenieras de sonido' }, 
    'inmunólogo': {'ms': 'inmunólogo', 'fs': 'inmunóloga', 'mp': 'inmunólogos', 'fp': 'inmunólogas' }, 
    'intendente': {'ms': 'intendente', 'fs': 'intendente', 'mp': 'intendentes', 'fp': 'intendentes' }, 
    'internista': {'ms': 'internista', 'fs': 'internista', 'mp': 'internistas', 'fp': 'internistas' }, 
    'intérprete': {'ms': 'intérprete', 'fs': 'intérprete', 'mp': 'intérpretes', 'fp': 'intérpretes' }, 
    'intérprete musical': {'ms': 'intérprete musical', 'fs': 'intérprete musical', 'mp': 'intérpretes musicales', 'fp': 'intérpretes musicales' }, 
    'inventor': {'ms': 'inventor', 'fs': 'inventora', 'mp': 'inventores', 'fp': 'inventoras' }, 
    'investigador': {'ms': 'investigador', 'fs': 'investigadora', 'mp': 'investigadores', 'fp': 'investigadoras' }, 
    'japonólogo': {'ms': 'japonólogo', 'fs': 'japonóloga', 'mp': 'japonólogos', 'fp': 'japonólogas' }, 
    'jefe de empresa': {'ms': 'jefe de empresa', 'fs': 'jefa de empresa', 'mp': 'jefes de empresa', 'fp': 'jefas de empresa' }, 
    'jinete hípico': {'ms': 'jinete hípico', 'fs': 'jinete hípica', 'mp': 'jinetes hípicos', 'fp': 'jinetes hípicas' }, 
    'jockey': {'ms': 'jockey', 'fs': 'jockey', 'mp': 'jockeys', 'fp': 'jockeys' }, 
    'joyero': {'ms': 'joyero', 'fs': 'joyera', 'mp': 'joyeros', 'fp': 'joyeras' }, 
    'jugador de bandy': {'ms': 'jugador de bandy', 'fs': 'jugadora de bandy', 'mp': 'jugadores de bandy', 'fp': 'jugadoras de bandy' }, 
    'jugador de bridge': {'ms': 'jugador de bridge', 'fs': 'jugadora de bridge', 'mp': 'jugadores de bridge', 'fp': 'jugadoras de bridge' }, 
    'jugador de críquet': {'ms': 'jugador de críquet', 'fs': 'jugadora de críquet', 'mp': 'jugadores de críquet', 'fp': 'jugadoras de críquet' }, 
    'jugador de fútbol sala': {'ms': 'jugador de fútbol sala', 'fs': 'jugadora de fútbol sala', 'mp': 'jugadores de fútbol sala', 'fp': 'jugadoras de fútbol sala' }, 
    'jugador de hockey': {'ms': 'jugador de hockey', 'fs': 'jugadora de hockey', 'mp': 'jugadores de hockey', 'fp': 'jugadoras de hockey' }, 
    'jugador de hockey sobre hielo': {'ms': 'jugador de hockey sobre hielo', 'fs': 'jugadora de hockey sobre hielo', 'mp': 'jugadores de hockey sobre hielo', 'fp': 'jugadoras de hockey sobre hielo' }, 
    'jugador de póquer': {'ms': 'jugador de póquer', 'fs': 'jugadora de póquer', 'mp': 'jugadores de póquer', 'fp': 'jugadoras de póquer' }, 
    'jugador de rugby union': {'ms': 'jugador de rugby union', 'fs': 'jugadora de rugby union', 'mp': 'jugadores de rugby union', 'fp': 'jugadoras de rugby union' }, 
    'jugador de sóftbol': {'ms': 'jugador de sóftbol', 'fs': 'jugadora de sóftbol', 'mp': 'jugadores de sóftbol', 'fp': 'jugadoras de sóftbol' }, 
    'jugador de squash': {'ms': 'jugador de squash', 'fs': 'jugadora de squash', 'mp': 'jugadores de squash', 'fp': 'jugadoras de squash' }, 
    'jugador de voleibol de playa': {'ms': 'jugador de voleibol de playa', 'fs': 'jugadora de voleibol de playa', 'mp': 'jugadores de voleibol de playa', 'fp': 'jugadoras de voleibol de playa' }, 
    'juez': {'ms': 'juez', 'fs': 'jueza', 'mp': 'jueces', 'fp': 'juezas' }, 
    'jugador de go': {'ms': 'jugador de go', 'fs': 'jugadora de go', 'mp': 'jugadores de go', 'fp': 'jugadoras de go' }, 
    'jurisconsulto': {'ms': 'jurisconsulto', 'fs': 'jurisconsulta', 'mp': 'jurisconsultos', 'fp': 'jurisconsultas' }, 
    'jurista': {'ms': 'jurista', 'fs': 'jurista', 'mp': 'juristas', 'fp': 'juristas' }, 
    'kayakista': {'ms': 'kayakista', 'fs': 'kayakista', 'mp': 'kayakistas', 'fp': 'kayakistas' }, 
    'karateka': {'ms': 'karateka', 'fs': 'karateka', 'mp': 'karatekas', 'fp': 'karatekas' }, 
    'lanzador de disco': {'ms': 'lanzador de disco', 'fs': 'lanzadora de disco', 'mp': 'lanzadores de disco', 'fp': 'lanzadoras de disco' }, 
    'lanzador de jabalina': {'ms': 'lanzador de jabalina', 'fs': 'lanzadora de jabalina', 'mp': 'lanzadores de jabalina', 'fp': 'lanzadoras de jabalina' }, 
    'lanzador de martillo': {'ms': 'lanzador de martillo', 'fs': 'lanzadora de martillo', 'mp': 'lanzadores de martillo', 'fp': 'lanzadoras de martillo' }, 
    'lavandera': {'ms': 'lavandera', 'fs': 'lavandera', 'mp': 'lavanderas', 'fp': 'lavanderas' }, 
    'letrista': {'ms': 'letrista', 'fs': 'letrista', 'mp': 'letristas', 'fp': 'letristas' }, 
    'lexicógrafo': {'ms': 'lexicógrafo', 'fs': 'lexicógrafa', 'mp': 'lexicógrafos', 'fp': 'lexicógrafas' }, 
    'librero': {'ms': 'librero', 'fs': 'librera', 'mp': 'libreros', 'fp': 'libreras' }, 
    'libretista': {'ms': 'libretista', 'fs': 'libretista', 'mp': 'libretistas', 'fp': 'libretistas' }, 
    'lingüista': {'ms': 'lingüista', 'fs': 'lingüista', 'mp': 'lingüistas', 'fp': 'lingüistas' }, 
    'literato': {'ms': 'literato', 'fs': 'literata', 'mp': 'literatos', 'fp': 'literatas' }, 
    'litógrafo': {'ms': 'litógrafo', 'fs': 'litógrafa', 'mp': 'litógrafos', 'fp': 'litógrafas' }, 
    'lobista': {'ms': 'lobista', 'fs': 'lobista', 'mp': 'lobistas', 'fp': 'lobistas' }, 
    'locutor': {'ms': 'locutor', 'fs': 'locutora', 'mp': 'locutores', 'fp': 'locutoras' }, 
    'luchador de artes marciales mixtas': {'ms': 'luchador de artes marciales mixtas', 'fs': 'luchadora de artes marciales mixtas', 'mp': 'luchadores de artes marciales mixtas', 'fp': 'luchadoras de artes marciales mixtas' }, 
    'luchador profesional': {'ms': 'luchador profesional', 'fs': 'luchadora profesional', 'mp': 'luchadores profesionales', 'fp': 'luchadoras profesionales' }, 
    'luger': {'ms': 'luger', 'fs': 'luger', 'mp': 'lugers', 'fp': 'lugers' }, 
    'maestro': {'ms': 'maestro', 'fs': 'maestra', 'mp': 'maestros', 'fp': 'maestras' }, 
    'maestro cervecero': {'ms': 'maestro cervecero', 'fs': 'maestra cervecera', 'mp': 'maestros cerveceros', 'fp': 'maestras cerveceras' }, 
    'maestro de ballet': {'ms': 'maestro de ballet', 'fs': 'maestra de ballet', 'mp': 'maestros de ballet', 'fp': 'maestras de ballet' }, 
    'maestro de ceremonias': {'ms': 'maestro de ceremonias', 'fs': 'maestra de ceremonias', 'mp': 'maestros de ceremonias', 'fp': 'maestras de ceremonias' }, 
    'maestro de teatro': {'ms': 'maestro de teatro', 'fs': 'maestra de teatro', 'mp': 'maestros de teatro', 'fp': 'maestras de teatro' }, 
    'magistrado': {'ms': 'magistrado', 'fs': 'magistrada', 'mp': 'magistrados', 'fp': 'magistradas' }, 
    'mago': {'ms': 'mago', 'fs': 'maga', 'mp': 'magos', 'fp': 'magas' }, 
    'manager': {'ms': 'manager', 'fs': 'manager', 'mp': 'managers', 'fp': 'managers' }, 
    'mandolinista': {'ms': 'mandolinista', 'fs': 'mandolinista', 'mp': 'mandolinistas', 'fp': 'mandolinistas' }, 
    'mangaka': {'ms': 'mangaka', 'fs': 'mangaka', 'mp': 'mangakas', 'fp': 'mangakas' }, 
    'maquillador': {'ms': 'maquillador', 'fs': 'maquilladora', 'mp': 'maquilladores', 'fp': 'maquilladoras' }, 
    'maratonista': {'ms': 'maratonista', 'fs': 'maratonista', 'mp': 'maratonistas', 'fp': 'maratonistas' }, 
    'marchante de arte': {'ms': 'marchante de arte', 'fs': 'marchante de arte', 'mp': 'marchantes de arte', 'fp': 'marchantes de arte' }, 
    'marino': {'ms': 'marino', 'fs': 'marina', 'mp': 'marinos', 'fp': 'marinas' }, 
    'matemático': {'ms': 'matemático', 'fs': 'matemática', 'mp': 'matemáticos', 'fp': 'matemáticas' }, 
    'matrona': {'ms': 'matrona', 'fs': 'matrona', 'mp': 'matronas', 'fp': 'matronas' }, 
    'mecenas': {'ms': 'mecenas', 'fs': 'mecenas', 'mp': 'mecenas', 'fp': 'mecenas' }, 
    'medallista': {'ms': 'medallista', 'fs': 'medallista', 'mp': 'medallistas', 'fp': 'medallistas' }, 
    'médico': {'ms': 'médico', 'fs': 'médico', 'mp': 'médicos', 'fp': 'médicos' }, 
    'médico especialista': {'ms': 'médico especialista', 'fs': 'médico especialista', 'mp': 'médicos especialistas', 'fp': 'médicos especialistas' }, 
    'medievalista': {'ms': 'medievalista', 'fs': 'medievalista', 'mp': 'medievalistas', 'fp': 'medievalistas' }, 
    'mediofondista': {'ms': 'mediofondista', 'fs': 'mediofondista', 'mp': 'mediofondistas', 'fp': 'mediofondistas' }, 
    'memorialista': {'ms': 'memorialista', 'fs': 'memorialista', 'mp': 'memorialistas', 'fp': 'memorialistas' }, 
    'mezzosoprano': {'ms': 'mezzosoprano', 'fs': 'mezzosoprano', 'mp': 'mezzosopranos', 'fp': 'mezzosopranos' }, 
    'microbiólogo': {'ms': 'microbiólogo', 'fs': 'microbióloga', 'mp': 'microbiólogos', 'fp': 'microbiólogas' }, 
    'miembro de la Knéset': {'ms': 'miembro de la Knéset', 'fs': 'miembro de la Knéset', 'mp': 'miembros de la Knéset', 'fp': 'miembros de la Knéset' }, 
    'militante de la resistencia': {'ms': 'militante de la resistencia', 'fs': 'militante de la resistencia', 'mp': 'militantes de la resistencia', 'fp': 'militantes de la resistencia' }, 
    'militar': {'ms': 'militar', 'fs': 'militar', 'mp': 'militares', 'fp': 'militares' }, 
    'misionero': {'ms': 'misionero', 'fs': 'misionera', 'mp': 'misioneros', 'fp': 'misioneras' }, 
    'místico': {'ms': 'místico', 'fs': 'mística', 'mp': 'místicos', 'fp': 'místicas' }, 
    'modelo': {'ms': 'modelo', 'fs': 'modelo', 'mp': 'modelos', 'fp': 'modelos' }, 
    'modelo artístico': {'ms': 'modelo artístico', 'fs': 'modelo artística', 'mp': 'modelos artísticos', 'fp': 'modelos artísticas' }, 
    'modelo erótico': {'ms': 'modelo erótico', 'fs': 'modelo erótica', 'mp': 'modelos eróticos', 'fp': 'modelos eróticas' }, 
    'modista': {'ms': 'modista', 'fs': 'modista', 'mp': 'modistas', 'fp': 'modistas' }, 
    'monja': {'ms': 'monja', 'fs': 'monja', 'mp': 'monjas', 'fp': 'monjas' }, 
    'montador': {'ms': 'montador', 'fs': 'montadora', 'mp': 'montadores', 'fp': 'montadoras' }, 
    'montañero': {'ms': 'montañero', 'fs': 'montañera', 'mp': 'montañeros', 'fp': 'montañeras' }, 
    'mosaiquista': {'ms': 'mosaiquista', 'fs': 'mosaiquista', 'mp': 'mosaiquistas', 'fp': 'mosaiquistas' }, 
    'multiinstrumentista': {'ms': 'multiinstrumentista', 'fs': 'multiinstrumentista', 'mp': 'multiinstrumentistas', 'fp': 'multiinstrumentistas' }, 
    'museólogo': {'ms': 'museólogo', 'fs': 'museóloga', 'mp': 'museólogos', 'fp': 'museólogas' }, 
    'musher': {'ms': 'musher', 'fs': 'musher', 'mp': 'mushers', 'fp': 'mushers' }, 
    'músico': {'ms': 'músico', 'fs': 'música', 'mp': 'músicos', 'fp': 'músicas' }, 
    'musicólogo': {'ms': 'musicólogo', 'fs': 'musicóloga', 'mp': 'musicólogos', 'fp': 'musicólogas' }, 
    'músico de jazz': {'ms': 'músico de jazz', 'fs': 'música de jazz', 'mp': 'músicos de jazz', 'fp': 'músicas de jazz' }, 
    'nadador': {'ms': 'nadador', 'fs': 'nadadora', 'mp': 'nadadores', 'fp': 'nadadoras' }, 
    'nadador sincronizado': {'ms': 'nadador sincronizado', 'fs': 'nadadora sincronizada', 'mp': 'nadadores sincronizados', 'fp': 'nadadoras sincronizadas' }, 
    'nana': {'ms': 'nana', 'fs': 'nana', 'mp': 'nanas', 'fp': 'nanas' }, 
    'narrador en off': {'ms': 'narrador en off', 'fs': 'narradora en off', 'mp': 'narradores en off', 'fp': 'narradoras en off' }, 
    'naturalista': {'ms': 'naturalista', 'fs': 'naturalista', 'mp': 'naturalistas', 'fp': 'naturalistas' }, 
    'navegante': {'ms': 'navegante', 'fs': 'navegante', 'mp': 'navegantes', 'fp': 'navegantes' }, 
    'neurocientífico': {'ms': 'neurocientífico', 'fs': 'neurocientífica', 'mp': 'neurocientíficos', 'fp': 'neurocientíficas' }, 
    'neurólogo': {'ms': 'neurólogo', 'fs': 'neuróloga', 'mp': 'neurólogos', 'fp': 'neurólogas' }, 
    'novelista': {'ms': 'novelista', 'fs': 'novelista', 'mp': 'novelistas', 'fp': 'novelistas' }, 
    'numismático': {'ms': 'numismático', 'fs': 'numismática', 'mp': 'numismáticos', 'fp': 'numismáticas' }, 
    'nutricionista': {'ms': 'nutricionista', 'fs': 'nutricionista', 'mp': 'nutricionistas', 'fp': 'nutricionistas' }, 
    'oboísta': {'ms': 'oboísta', 'fs': 'oboísta', 'mp': 'oboístas', 'fp': 'oboístas' }, 
    'obstetra': {'ms': 'obstetra', 'fs': 'obstetra', 'mp': 'obstetras', 'fp': 'obstetras' }, 
    'oceanógrafo': {'ms': 'oceanógrafo', 'fs': 'oceanógrafa', 'mp': 'oceanógrafos', 'fp': 'oceanógrafas' }, 
    'oficial': {'ms': 'oficial', 'fs': 'oficial', 'mp': 'oficiales', 'fp': 'oficiales' }, 
    'oftalmólogo': {'ms': 'oftalmólogo', 'fs': 'oftalmóloga', 'mp': 'oftalmólogos', 'fp': 'oftalmólogas' }, 
    'oncólogo': {'ms': 'oncólogo', 'fs': 'oncóloga', 'mp': 'oncólogos', 'fp': 'oncólogas' }, 
    'orador motivacional': {'ms': 'orador motivacional', 'fs': 'oradora motivacional', 'mp': 'oradores motivacionales', 'fp': 'oradoras motivacionales' }, 
    'organista': {'ms': 'organista', 'fs': 'organista', 'mp': 'organistas', 'fp': 'organistas' }, 
    'organizador sindical': {'ms': 'organizador sindical', 'fs': 'organizadora sindical', 'mp': 'organizadores sindicales', 'fp': 'organizadoras sindicales' }, 
    'orientador': {'ms': 'orientador', 'fs': 'orientadora', 'mp': 'orientadores', 'fp': 'orientadoras' }, 
    'ornitólogo': {'ms': 'ornitólogo', 'fs': 'ornitóloga', 'mp': 'ornitólogos', 'fp': 'ornitólogas' }, 
    'pacifista': {'ms': 'pacifista', 'fs': 'pacifista', 'mp': 'pacifistas', 'fp': 'pacifistas' }, 
    'paleontólogo': {'ms': 'paleontólogo', 'fs': 'paleontóloga', 'mp': 'paleontólogos', 'fp': 'paleontólogas' }, 
    'paracaidista': {'ms': 'paracaidista', 'fs': 'paracaidista', 'mp': 'paracaidistas', 'fp': 'paracaidistas' }, 
    'párroco': {'ms': 'párroco', 'fs': 'párroca', 'mp': 'párrocos', 'fp': 'párrocas' }, 
    'pastor': {'ms': 'pastor', 'fs': 'pastora', 'mp': 'pastores', 'fp': 'pastoras' }, 
    'patinador artístico sobre hielo': {'ms': 'patinador artístico sobre hielo', 'fs': 'patinadora artística sobre hielo', 'mp': 'patinadores artísticos sobre hielo', 'fp': 'patinadoras artísticas sobre hielo' }, 
    'patinador de velocidad': {'ms': 'patinador de velocidad', 'fs': 'patinadora de velocidad', 'mp': 'patinadores de velocidad', 'fp': 'patinadoras de velocidad' }, 
    'participante de concurso de belleza': {'ms': 'participante de concurso de belleza', 'fs': 'participante de concurso de belleza', 'mp': 'participantes de concursos de belleza', 'fp': 'participantes de concursos de belleza' }, 
    'payaso': {'ms': 'payaso', 'fs': 'payasa', 'mp': 'payasos', 'fp': 'payasas' }, 
    'pedagogo': {'ms': 'pedagogo', 'fs': 'pedagoga', 'mp': 'pedagogos', 'fp': 'pedagogas' }, 
    'pediatra': {'ms': 'pediatra', 'fs': 'pediatra', 'mp': 'pediatras', 'fp': 'pediatras' }, 
    'peluquero': {'ms': 'peluquero', 'fs': 'peluquera', 'mp': 'peluqueros', 'fp': 'peluqueras' }, 
    'pentatleta': {'ms': 'pentatleta', 'fs': 'pentatleta', 'mp': 'pentatletas', 'fp': 'pentatletas' }, 
    'percusionista': {'ms': 'percusionista', 'fs': 'percusionista', 'mp': 'percusionistas', 'fp': 'percusionistas' }, 
    'performer': {'ms': 'performer', 'fs': 'performer', 'mp': 'performers', 'fp': 'performers' }, 
    'perfumista': {'ms': 'perfumista', 'fs': 'perfumista', 'mp': 'perfumistas', 'fp': 'perfumistas' }, 
    'periodista': {'ms': 'periodista', 'fs': 'periodista', 'mp': 'periodistas', 'fp': 'periodistas' }, 
    'periodista científico': {'ms': 'periodista científico', 'fs': 'periodista científica', 'mp': 'periodistas científicos', 'fp': 'periodistas científicas' }, 
    'periodista político': {'ms': 'periodista político', 'fs': 'periodista política', 'mp': 'periodistas políticos', 'fp': 'periodistas políticas' }, 
    'pianista': {'ms': 'pianista', 'fs': 'pianista', 'mp': 'pianistas', 'fp': 'pianistas' }, 
    'piloto de automovilismo': {'ms': 'piloto de automovilismo', 'fs': 'piloto de automovilismo', 'mp': 'pilotos de automovilismo', 'fp': 'pilotos de automovilismo' }, 
    'piloto de carreras': {'ms': 'piloto de carreras', 'fs': 'piloto de carreras', 'mp': 'pilotos de carreras', 'fp': 'pilotos de carreras' }, 
    'piloto de guerra': {'ms': 'piloto de guerra', 'fs': 'piloto de guerra', 'mp': 'pilotos de guerra', 'fp': 'pilotos de guerra' }, 
    'piloto de helicóptero': {'ms': 'piloto de helicóptero', 'fs': 'piloto de helicóptero', 'mp': 'pilotos de helicóptero', 'fp': 'pilotos de helicóptero' }, 
    'piloto de motociclismo': {'ms': 'piloto de motociclismo', 'fs': 'piloto de motociclismo', 'mp': 'pilotos de motociclismo', 'fp': 'pilotos de motociclismo' }, 
    'piloto de pruebas': {'ms': 'piloto de pruebas', 'fs': 'piloto de pruebas', 'mp': 'pilotos de pruebas', 'fp': 'pilotos de pruebas' }, 
    'pintor': {'ms': 'pintor', 'fs': 'pintora', 'mp': 'pintores', 'fp': 'pintoras' }, 
    'pintor retratista': {'ms': 'pintor retratista', 'fs': 'pintora retratista', 'mp': 'pintores retratistas', 'fp': 'pintoras retratistas' }, 
    'piragüista': {'ms': 'piragüista', 'fs': 'piragüista', 'mp': 'piragüistas', 'fp': 'piragüistas' }, 
    'playmate': {'ms': 'playmate', 'fs': 'playmate', 'mp': 'playmates', 'fp': 'playmates' }, 
    'podcaster': {'ms': 'podcaster', 'fs': 'podcaster', 'mp': 'podcasters', 'fp': 'podcasters' }, 
    'poeta': {'ms': 'poeta', 'fs': 'poeta', 'mp': 'poetas', 'fp': 'poetas' }, 
    'político': {'ms': 'político', 'fs': 'política', 'mp': 'políticos', 'fp': 'políticas' }, 
    'politólogo': {'ms': 'politólogo', 'fs': 'politóloga', 'mp': 'politólogos', 'fp': 'politólogas' }, 
    'portavoz': {'ms': 'portavoz', 'fs': 'portavoz', 'mp': 'portavoces', 'fp': 'portavoces' }, 
    'prehistoriador': {'ms': 'prehistoriador', 'fs': 'prehistoriadora', 'mp': 'prehistoriadores', 'fp': 'prehistoriadoras' }, 
    'presentador': {'ms': 'presentador', 'fs': 'presentadora', 'mp': 'presentadores', 'fp': 'presentadoras' }, 
    'presentador de noticias': {'ms': 'presentador de noticias', 'fs': 'presentadora de noticias', 'mp': 'presentadores de noticias', 'fp': 'presentadoras de noticias' }, 
    'presentador de televisión': {'ms': 'presentador de televisión', 'fs': 'presentadora de televisión', 'mp': 'presentadores de televisión', 'fp': 'presentadoras de televisión' }, 
    'princesa': {'ms': 'princesa', 'fs': 'princesa', 'mp': 'princesas', 'fp': 'princesas' }, 
    'productor': {'ms': 'productor', 'fs': 'productora', 'mp': 'productores', 'fp': 'productoras' }, 
    'productor de cine': {'ms': 'productor de cine', 'fs': 'productora de cine', 'mp': 'productores de cine', 'fp': 'productoras de cine' }, 
    'productor de radio': {'ms': 'productor de radio', 'fs': 'productora de radio', 'mp': 'productores de radio', 'fp': 'productoras de radio' }, 
    'productor de televisión': {'ms': 'productor de televisión', 'fs': 'productora de televisión', 'mp': 'productores de televisión', 'fp': 'productoras de televisión' }, 
    'productor discográfico': {'ms': 'productor discográfico', 'fs': 'productora discográfica', 'mp': 'productores discográficos', 'fp': 'productoras discográficas' }, 
    'productor ejecutivo': {'ms': 'productor ejecutivo', 'fs': 'productora ejecutiva', 'mp': 'productores ejecutivos', 'fp': 'productoras ejecutivas' }, 
    'profesor': {'ms': 'profesor', 'fs': 'profesora', 'mp': 'profesores', 'fp': 'profesoras' }, 
    'profesor de educación superior': {'ms': 'profesor de educación superior', 'fs': 'profesora de educación superior', 'mp': 'profesores de educación superior', 'fp': 'profesoras de educación superior' }, 
    'profesor de música': {'ms': 'profesor de música', 'fs': 'profesora de música', 'mp': 'profesores de música', 'fp': 'profesoras de música' }, 
    'profesor de voz': {'ms': 'profesor de voz', 'fs': 'profesora de voz', 'mp': 'profesores de voz', 'fp': 'profesoras de voz' }, 
    'programador': {'ms': 'programador', 'fs': 'programadora', 'mp': 'programadores', 'fp': 'programadoras' }, 
    'prosista': {'ms': 'prosista', 'fs': 'prosista', 'mp': 'prosistas', 'fp': 'prosistas' }, 
    'prostituto': {'ms': 'prostituto', 'fs': 'prostituta', 'mp': 'prostitutos', 'fp': 'prostitutas' }, 
    'psicoanalista': {'ms': 'psicoanalista', 'fs': 'psicoanalista', 'mp': 'psicoanalistas', 'fp': 'psicoanalistas' }, 
    'psicólogo': {'ms': 'psicólogo', 'fs': 'psicóloga', 'mp': 'psicólogos', 'fp': 'psicólogas' }, 
    'psicoterapeuta': {'ms': 'psicoterapeuta', 'fs': 'psicoterapeuta', 'mp': 'psicoterapeutas', 'fp': 'psicoterapeutas' }, 
    'psiquiatra': {'ms': 'psiquiatra', 'fs': 'psiquiatra', 'mp': 'psiquiatras', 'fp': 'psiquiatras' }, 
    'publicista': {'ms': 'publicista', 'fs': 'publicista', 'mp': 'publicistas', 'fp': 'publicistas' }, 
    'químico': {'ms': 'químico', 'fs': 'química', 'mp': 'químicos', 'fp': 'químicas' }, 
    'rabino': {'ms': 'rabino', 'fs': 'rabina', 'mp': 'rabinos', 'fp': 'rabinas' }, 
    'rapero': {'ms': 'rapero', 'fs': 'rapera', 'mp': 'raperos', 'fp': 'raperas' }, 
    'realizador': {'ms': 'realizador', 'fs': 'realizadora', 'mp': 'realizadores', 'fp': 'realizadoras' }, 
    'redactor en jefe': {'ms': 'redactor en jefe', 'fs': 'redactora en jefe', 'mp': 'redactores en jefe', 'fp': 'redactoras en jefe' }, 
    'redactor de discursos': {'ms': 'redactor de discursos', 'fs': 'redactora de discursos', 'mp': 'redactores de discursos', 'fp': 'redactoras de discursos' }, 
    'regatista': {'ms': 'regatista', 'fs': 'regatista', 'mp': 'regatistas', 'fp': 'regatistas' }, 
    'religioso': {'ms': 'religioso', 'fs': 'religiosa', 'mp': 'religiosos', 'fp': 'religiosas' }, 
    'remero': {'ms': 'remero', 'fs': 'remera', 'mp': 'remeros', 'fp': 'remeras' }, 
    'reportero': {'ms': 'reportero', 'fs': 'reportera', 'mp': 'reporteros', 'fp': 'reporteras' }, 
    'restaurador': {'ms': 'restaurador', 'fs': 'restauradora', 'mp': 'restauradores', 'fp': 'restauradoras' }, 
    'revolucionario': {'ms': 'revolucionario', 'fs': 'revolucionaria', 'mp': 'revolucionarios', 'fp': 'revolucionarias' }, 
    'sacerdote': {'ms': 'sacerdote', 'fs': 'sacerdote', 'mp': 'sacerdotes', 'fp': 'sacerdotes' }, 
    'salonnière': {'ms': 'salonnière', 'fs': 'salonnière', 'mp': 'salonnières', 'fp': 'salonnières' }, 
    'saltador': {'ms': 'saltador', 'fs': 'saltadora', 'mp': 'saltadores', 'fp': 'saltadoras' }, 
    'saltador de altura': {'ms': 'saltador de altura', 'fs': 'saltadora de altura', 'mp': 'saltadores de altura', 'fp': 'saltadoras de altura' }, 
    'saltador de esquí': {'ms': 'saltador de esquí', 'fs': 'saltadora de esquí', 'mp': 'saltadores de esquí', 'fp': 'saltadoras de esquí' }, 
    'saltador de longitud': {'ms': 'saltador de longitud', 'fs': 'saltadora de longitud', 'mp': 'saltadores de longitud', 'fp': 'saltadoras de longitud' }, 
    'saltador de pértiga': {'ms': 'saltador de pértiga', 'fs': 'saltadora de pértiga', 'mp': 'saltadores de pértiga', 'fp': 'saltadoras de pértiga' }, 
    'saltador de triple salto': {'ms': 'saltador de triple salto', 'fs': 'saltadora de triple salto', 'mp': 'saltadores de triple salto', 'fp': 'saltadoras de triple salto' }, 
    'samurái': {'ms': 'samurái', 'fs': 'samurái', 'mp': 'samuráis', 'fp': 'samuráis' }, 
    'sastre': {'ms': 'sastre', 'fs': 'sastre', 'mp': 'sastres', 'fp': 'sastres' }, 
    'saxofonista': {'ms': 'saxofonista', 'fs': 'saxofonista', 'mp': 'saxofonistas', 'fp': 'saxofonistas' }, 
    'secretario': {'ms': 'secretario', 'fs': 'secretaria', 'mp': 'secretarios', 'fp': 'secretarias' }, 
    'seiyū': {'ms': 'seiyū', 'fs': 'seiyū', 'mp': 'seiyūs', 'fp': 'seiyūs' }, 
    'sindicalista': {'ms': 'sindicalista', 'fs': 'sindicalista', 'mp': 'sindicalistas', 'fp': 'sindicalistas' }, 
    'snowboarder': {'ms': 'snowboarder', 'fs': 'snowboarder', 'mp': 'snowboarders', 'fp': 'snowboarders' }, 
    'socialité': {'ms': 'socialité', 'fs': 'socialité', 'mp': 'socialités', 'fp': 'socialités' }, 
    'sociólogo': {'ms': 'sociólogo', 'fs': 'socióloga', 'mp': 'sociólogos', 'fp': 'sociólogas' }, 
    'soldado': {'ms': 'soldado', 'fs': 'soldado', 'mp': 'soldados', 'fp': 'soldados' }, 
    'solista': {'ms': 'solista', 'fs': 'solista', 'mp': 'solistas', 'fp': 'solistas' }, 
    'supermodelo': {'ms': 'supermodelo', 'fs': 'supermodelo', 'mp': 'supermodelos', 'fp': 'supermodelos' }, 
    'soprano': {'ms': 'soprano', 'fs': 'soprana', 'mp': 'sopranos', 'fp': 'sopranas' }, 
    'sufragete': {'ms': 'sufragete', 'fs': 'sufragete', 'mp': 'sufragetes', 'fp': 'sufragetes' }, 
    'surfista': {'ms': 'surfista', 'fs': 'surfista', 'mp': 'surfistas', 'fp': 'surfistas' }, 
    'talud': {'ms': 'talud', 'fs': 'talud', 'mp': 'taluds', 'fp': 'taluds' }, 
    'tatuador': {'ms': 'tatuador', 'fs': 'tatuadora', 'mp': 'tatuadores', 'fp': 'tatuadoras' }, 
    'tarento': {'ms': 'tarento', 'fs': 'tarento', 'mp': 'tarentos', 'fp': 'tarentos' }, 
    'técnico en emergencias médicas': {'ms': 'técnico en emergencias médicas', 'fs': 'técnica en emergencias médicas', 'mp': 'técnicos en emergencias médicas', 'fp': 'técnicas en emergencias médicas' }, 
    'tejedor': {'ms': 'tejedor', 'fs': 'tejedora', 'mp': 'tejedors', 'fp': 'tejedoras' }, 
    'tendero': {'ms': 'tendero', 'fs': 'tendera', 'mp': 'tenderos', 'fp': 'tenderas' }, 
    'tenista': {'ms': 'tenista', 'fs': 'tenista', 'mp': 'tenistas', 'fp': 'tenistas' }, 
    'tenista de mesa': {'ms': 'tenista de mesa', 'fs': 'tenista de mesa', 'mp': 'tenistas de mesa', 'fp': 'tenistas de mesa' }, 
    'tenista en silla de ruedas': {'ms': 'tenista en silla de ruedas', 'fs': 'tenista en silla de ruedas', 'mp': 'tenistas en silla de ruedas', 'fp': 'tenistas en silla de ruedas' }, 
    'teólogo': {'ms': 'teólogo', 'fs': 'teóloga', 'mp': 'teólogos', 'fp': 'teólogas' }, 
    'teórico literario': {'ms': 'teórico literario', 'fs': 'teórica literaria', 'mp': 'teóricos literarios', 'fp': 'teóricas literarias' }, 
    'teórico racial': {'ms': 'teórico racial', 'fs': 'teórica racial', 'mp': 'teóricos raciales', 'fp': 'teóricas raciales' }, 
    'teclista': {'ms': 'teclista', 'fs': 'teclista', 'mp': 'teclistas', 'fp': 'teclistas' }, 
    'tipógrafo': {'ms': 'tipógrafo', 'fs': 'tipógrafa', 'mp': 'tipógrafos', 'fp': 'tipógrafas' }, 
    'tirador': {'ms': 'tirador', 'fs': 'tiradora', 'mp': 'tiradores', 'fp': 'tiradoras' }, 
    'titiritero': {'ms': 'titiritero', 'fs': 'titiritera', 'mp': 'titiriteros', 'fp': 'titiriteras' }, 
    'torturador': {'ms': 'torturador', 'fs': 'torturadora', 'mp': 'torturadores', 'fp': 'torturadoras' }, 
    'traductor': {'ms': 'traductor', 'fs': 'traductora', 'mp': 'traductores', 'fp': 'traductoras' }, 
    'traductor de la Biblia': {'ms': 'traductor de la Biblia', 'fs': 'traductora de la Biblia', 'mp': 'traductores de la Biblia', 'fp': 'traductoras de la Biblia' }, 
    'triatleta': {'ms': 'triatleta', 'fs': 'triatleta', 'mp': 'triatletas', 'fp': 'triatletas' }, 
    'trompetista': {'ms': 'trompetista', 'fs': 'trompetista', 'mp': 'trompetistas', 'fp': 'trompetistas' }, 
    'trompista': {'ms': 'trompista', 'fs': 'trompista', 'mp': 'trompistas', 'fp': 'trompistas' }, 
    'ufólogo': {'ms': 'ufólogo', 'fs': 'ufóloga', 'mp': 'ufólogos', 'fp': 'ufólogas' }, 
    'ultramaratonista': {'ms': 'ultramaratonista', 'fs': 'ultramaratonista', 'mp': 'ultramaratonistas', 'fp': 'ultramaratonistas' }, 
    'urbanista': {'ms': 'urbanista', 'fs': 'urbanista', 'mp': 'urbanistas', 'fp': 'urbanistas' }, 
    'vallista': {'ms': 'vallista', 'fs': 'vallista', 'mp': 'vallistas', 'fp': 'vallistas' }, 
    'velocista': {'ms': 'velocista', 'fs': 'velocista', 'mp': 'velocistas', 'fp': 'velocistas' }, 
    'verdugo': {'ms': 'verdugo', 'fs': 'verdugo', 'mp': 'verdugos', 'fp': 'verdugos' }, 
    'veterinario': {'ms': 'veterinario', 'fs': 'veterinaria', 'mp': 'veterinarios', 'fp': 'veterinarias' }, 
    'videoartista': {'ms': 'videoartista', 'fs': 'videoartista', 'mp': 'videoartistas', 'fp': 'videoartistas' }, 
    'videógrafo': {'ms': 'videógrafo', 'fs': 'videógrafa', 'mp': 'videógrafos', 'fp': 'videógrafas' }, 
    'violinista': {'ms': 'violinista', 'fs': 'violinista', 'mp': 'violinistas', 'fp': 'violinistas' }, 
    'violonchelista': {'ms': 'violonchelista', 'fs': 'violonchelista', 'mp': 'violonchelistas', 'fp': 'violonchelistas' }, 
    'viticultor': {'ms': 'viticultor', 'fs': 'viticultora', 'mp': 'viticultores', 'fp': 'viticultoras' }, 
    'vitralista': {'ms': 'vitralista', 'fs': 'vitralista', 'mp': 'vitralistas', 'fp': 'vitralistas' }, 
    'vocalista': {'ms': 'vocalista', 'fs': 'vocalista', 'mp': 'vocalistas', 'fp': 'vocalistas' }, 
    'volatinero': {'ms': 'volatinero', 'fs': 'volatinero', 'mp': 'volatineros', 'fp': 'volatineros' }, 
    'voleibolista': {'ms': 'voleibolista', 'fs': 'voleibolista', 'mp': 'voleibolistas', 'fp': 'voleibolistas' }, 
    'vulcanólogo': {'ms': 'vulcanólogo', 'fs': 'vulcanóloga', 'mp': 'vulcanólogos', 'fp': 'vulcanólogas' }, 
    'wikipedista': {'ms': 'wikipedista', 'fs': 'wikipedista', 'mp': 'wikipedistas', 'fp': 'wikipedistas' }, 
    'windsurfista': {'ms': 'windsurfista', 'fs': 'windsurfista', 'mp': 'windsurfistas', 'fp': 'windsurfistas' }, 
    'yudoca': {'ms': 'yudoca', 'fs': 'yudoca', 'mp': 'yudocas', 'fp': 'yudocas' }, 
    'youtuber': {'ms': 'youtuber', 'fs': 'youtuber', 'mp': 'youtubers', 'fp': 'youtubers' }, 
    'zoólogo': {'ms': 'zoólogo', 'fs': 'zoóloga', 'mp': 'zoólogos', 'fp': 'zoólogas' }, 
}

#https://query.wikidata.org/#SELECT%20DISTINCT%20%3Fitem%20%3FitemLabel%0AWHERE%20{%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ6256.%0A%20%20SERVICE%20wikibase%3Alabel%20{%20bd%3AserviceParam%20wikibase%3Alanguage%20%22es%2Cen%22%20}%0A}
nacionalidades = {
    'Afganistán': {'ms': 'afgano', 'fs': 'afgana', 'mp': 'afganos', 'fp': 'afganas' }, 
    'Albania': {'ms': 'albanés', 'fs': 'albanesa', 'mp': 'albaneses', 'fp': 'albanesas' }, 
    'Alemania': {'ms': 'alemán', 'fs': 'alemana', 'mp': 'alemanes', 'fp': 'alemanas' }, 
    'Andorra': {'ms': 'andorrano', 'fs': 'andorrana', 'mp': 'andorranos', 'fp': 'andorranas' }, 
    'Angola': {'ms': 'angoleño', 'fs': 'angoleña', 'mp': 'angoleños', 'fp': 'angoleñas' }, 
    'Antigua y Barbuda': {'ms': 'antiguano', 'fs': 'antiguana', 'mp': 'antiguanos', 'fp': 'antiguanas' }, 
    'Arabia Saudita': {'ms': 'saudí', 'fs': 'saudí', 'mp': 'saudíes', 'fp': 'saudíes' }, 
    'Argelia': {'ms': 'argelino', 'fs': 'argelina', 'mp': 'argelinos', 'fp': 'argelinas' }, 
    'Argentina': {'ms': 'argentino', 'fs': 'argentina', 'mp': 'argentinos', 'fp': 'argentinas' }, 
    'Armenia': {'ms': 'armenio', 'fs': 'armenia', 'mp': 'armenios', 'fp': 'armenias' }, 
    'Australia': {'ms': 'australiano', 'fs': 'australiana', 'mp': 'australianos', 'fp': 'australianas' }, 
    'Austria': {'ms': 'austríaco', 'fs': 'austríaca', 'mp': 'austríacos', 'fp': 'austríacas' }, 
    'Azerbaiyán': {'ms': 'azerbaiyano', 'fs': 'azerbaiyana', 'mp': 'azerbaiyanos', 'fp': 'azerbaiyanas' }, 
    'Bahamas': {'ms': 'bahameño', 'fs': 'bahameña', 'mp': 'bahameños', 'fp': 'bahameñas' }, 
    'Bangladés': {'ms': 'bangladesí', 'fs': 'bangladesí', 'mp': 'bangladesíes', 'fp': 'bangladesíes' }, 
    'Barbados': {'ms': 'barbadense', 'fs': 'barbadense', 'mp': 'barbadenses', 'fp': 'barbadenses' }, 
    'Baréin': {'ms': 'bareiní', 'fs': 'bareiní', 'mp': 'bareiníes', 'fp': 'bareiníes' }, 
    'Bélgica': {'ms': 'belga', 'fs': 'belga', 'mp': 'belgas', 'fp': 'belgas' }, 
    'Belice': {'ms': 'beliceño', 'fs': 'beliceña', 'mp': 'beliceños', 'fp': 'beliceñas' }, 
    'Benín': {'ms': 'beninés', 'fs': 'beninesa', 'mp': 'benineses', 'fp': 'beninesas' }, 
    'Bielorrusia': {'ms': 'bielorruso', 'fs': 'bielorrusa', 'mp': 'bielorrusos', 'fp': 'bielorrusas' }, 
    'Birmania': {'ms': 'birmano', 'fs': 'birmana', 'mp': 'birmanos', 'fp': 'birmanas' }, 
    'Bolivia': {'ms': 'boliviano', 'fs': 'boliviana', 'mp': 'bolivianos', 'fp': 'bolivianas' }, 
    'Bosnia y Herzegovina': {'ms': 'bosnio', 'fs': 'bosnia', 'mp': 'bosnios', 'fp': 'bosnias' }, 
    'Botsuana': {'ms': 'botsuano', 'fs': 'botsuana', 'mp': 'botsuanos', 'fp': 'botsuanas' }, 
    'Brasil': {'ms': 'brasileño', 'fs': 'brasileña', 'mp': 'brasileños', 'fp': 'brasileñas' }, 
    'Brunéi': {'ms': 'bruneano', 'fs': 'bruneana', 'mp': 'bruneanos', 'fp': 'bruneanas' }, 
    'Bulgaria': {'ms': 'búlgaro', 'fs': 'búlgara', 'mp': 'búlgaros', 'fp': 'búlgaras' }, 
    'Burkina Faso': {'ms': 'burkinés', 'fs': 'burkinesa', 'mp': 'burkineses', 'fp': 'burkinesas' }, 
    'Burundi': {'ms': 'burundés', 'fs': 'burundesa', 'mp': 'burundeses', 'fp': 'burundesas' }, 
    'Bután': {'ms': 'butanés', 'fs': 'butanesa', 'mp': 'butaneses', 'fp': 'butanesas' }, 
    'Cabo Verde': {'ms': 'caboverdiano', 'fs': 'caboverdiana', 'mp': 'caboverdianos', 'fp': 'caboverdianas' }, 
    'Camboya': {'ms': 'camboyano', 'fs': 'camboyana', 'mp': 'camboyanos', 'fp': 'camboyanas' }, 
    'Camerún': {'ms': 'camerunés', 'fs': 'camerunesa', 'mp': 'cameruneses', 'fp': 'camerunesas' }, 
    'Canadá': {'ms': 'canadiense', 'fs': 'canadiense', 'mp': 'canadienses', 'fp': 'canadienses' }, 
    'Catar': {'ms': 'catarí', 'fs': 'catarí', 'mp': 'cataríes', 'fp': 'cataríes' }, 
    'Chad': {'ms': 'chadiano', 'fs': 'chadiana', 'mp': 'chadianos', 'fp': 'chadianas' }, 
    'Chile': {'ms': 'chileno', 'fs': 'chilena', 'mp': 'chilenos', 'fp': 'chilenas' }, 
    'Chipre': {'ms': 'chipriota', 'fs': 'chipriota', 'mp': 'chipriotas', 'fp': 'chipriotas' }, 
    'Ciudad del Vaticano': {'ms': 'vaticano', 'fs': 'vaticana', 'mp': 'vaticanos', 'fp': 'vaticanas' }, 
    'Colombia': {'ms': 'colombiano', 'fs': 'colombiana', 'mp': 'colombianos', 'fp': 'colombianas' }, 
    'Comoras': {'ms': 'comorense', 'fs': 'comorense', 'mp': 'comorenses', 'fp': 'comorenses' }, 
    'Corea del Norte': {'ms': 'norcoreano', 'fs': 'norcoreana', 'mp': 'norcoreanos', 'fp': 'norcoreanas' }, 
    'Corea del Sur': {'ms': 'surcoreano', 'fs': 'surcoreana', 'mp': 'surcoreanos', 'fp': 'surcoreanas' }, 
    'Costa de Marfil': {'ms': 'marfileño', 'fs': 'marfileña', 'mp': 'marfileños', 'fp': 'marfileñas' }, 
    'Costa Rica': {'ms': 'costarricense', 'fs': 'costarricense', 'mp': 'costarricenses', 'fp': 'costarricenses' }, 
    'Croacia': {'ms': 'croata', 'fs': 'croata', 'mp': 'croatas', 'fp': 'croatas' }, 
    'Cuba': {'ms': 'cubano', 'fs': 'cubana', 'mp': 'cubanos', 'fp': 'cubanas' }, 
    'Dinamarca': {'ms': 'danés', 'fs': 'danesa', 'mp': 'daneses', 'fp': 'danesas' }, 
    'Dominica': {'ms': 'dominiqués', 'fs': 'dominiquesa', 'mp': 'dominiqueses', 'fp': 'dominiquesas' }, 
    'Ecuador': {'ms': 'ecuatoriano', 'fs': 'ecuatoriana', 'mp': 'ecuatorianos', 'fp': 'ecuatorianas' }, 
    'Egipto': {'ms': 'egipcio', 'fs': 'egipcia', 'mp': 'egipcios', 'fp': 'egipcias' }, 
    'El Salvador': {'ms': 'salvadoreño', 'fs': 'salvadoreña', 'mp': 'salvadoreños', 'fp': 'salvadoreñas' }, 
    'Emiratos Árabes Unidos': {'ms': 'emiratí', 'fs': 'emiratí', 'mp': 'emiratíes', 'fp': 'emiratíes' }, 
    'Eritrea': {'ms': 'eritreo', 'fs': 'eritrea', 'mp': 'eritreos', 'fp': 'eritreas' }, 
    'Eslovaquia': {'ms': 'eslovaco', 'fs': 'eslovaca', 'mp': 'eslovacos', 'fp': 'eslovacas' }, 
    'Eslovenia': {'ms': 'esloveno', 'fs': 'eslovena', 'mp': 'eslovenos', 'fp': 'eslovenas' }, 
    'España': {'ms': 'español', 'fs': 'española', 'mp': 'españoles', 'fp': 'españolas' }, 
    'Estados Unidos': {'ms': 'estadounidense', 'fs': 'estadounidense', 'mp': 'estadounidenses', 'fp': 'estadounidenses' }, 
    'Estonia': {'ms': 'estonio', 'fs': 'estonia', 'mp': 'estonios', 'fp': 'estonias' }, 
    'Etiopía': {'ms': 'etíope', 'fs': 'etíope', 'mp': 'etíopes', 'fp': 'etíopes' }, 
    'Filipinas': {'ms': 'filipino', 'fs': 'filipina', 'mp': 'filipinos', 'fp': 'filipinas' }, 
    'Finlandia': {'ms': 'finlandés', 'fs': 'finlandesa', 'mp': 'finlandeses', 'fp': 'finlandesas' }, 
    'Fiyi': {'ms': 'fiyiano', 'fs': 'fiyiana', 'mp': 'fiyianos', 'fp': 'fiyianas' }, 
    'Francia': {'ms': 'francés', 'fs': 'francesa', 'mp': 'franceses', 'fp': 'francesas' }, 
    'Gabón': {'ms': 'gabonés', 'fs': 'gabonesa', 'mp': 'gaboneses', 'fp': 'gabonesas' }, 
    'Gambia': {'ms': 'gambiano', 'fs': 'gambiana', 'mp': 'gambianos', 'fp': 'gambianas' }, 
    'Georgia': {'ms': 'georgiano', 'fs': 'georgiana', 'mp': 'georgianos', 'fp': 'georgianas' }, 
    'Ghana': {'ms': 'ghanés', 'fs': 'ghanesa', 'mp': 'ghaneses', 'fp': 'ghanesas' }, 
    'Granada': {'ms': 'granadino', 'fs': 'granadina', 'mp': 'granadinos', 'fp': 'granadinas' }, 
    'Grecia': {'ms': 'griego', 'fs': 'griega', 'mp': 'griegos', 'fp': 'griegas' }, 
    'Guatemala': {'ms': 'guatemalteco', 'fs': 'guatemalteca', 'mp': 'guatemaltecos', 'fp': 'guatemaltecas' }, 
    'Guinea': {'ms': 'guineano', 'fs': 'guineana', 'mp': 'guineanos', 'fp': 'guineanas' }, 
    'Guinea Ecuatorial': {'ms': 'ecuatoguineano', 'fs': 'ecuatoguineana', 'mp': 'ecuatoguineanos', 'fp': 'ecuatoguineanas' }, 
    'Guinea-Bisáu': {'ms': 'guineano', 'fs': 'guineana', 'mp': 'guineanos', 'fp': 'guineanas' }, 
    'Guyana': {'ms': 'guyanés', 'fs': 'guyanesa', 'mp': 'guyaneses', 'fp': 'guyanesas' }, 
    'Haití': {'ms': 'haitiano', 'fs': 'haitiana', 'mp': 'haitianos', 'fp': 'haitianas' }, 
    'Honduras': {'ms': 'hondureño', 'fs': 'hondureña', 'mp': 'hondureños', 'fp': 'hondureñas' }, 
    'Hungría': {'ms': 'húngaro', 'fs': 'húngara', 'mp': 'húngaros', 'fp': 'húngaras' }, 
    'Imperio ruso': {'ms': 'ruso', 'fs': 'rusa', 'mp': 'rusos', 'fp': 'rusas' }, 
    'India': {'ms': 'indio', 'fs': 'india', 'mp': 'indios', 'fp': 'indias' }, 
    'Indonesia': {'ms': 'indonesio', 'fs': 'indonesia', 'mp': 'indonesios', 'fp': 'indonesias' }, 
    'Irak': {'ms': 'iraquí', 'fs': 'iraquí', 'mp': 'iraquíes', 'fp': 'iraquíes' }, 
    'Irán': {'ms': 'iraní', 'fs': 'iraní', 'mp': 'iraníes', 'fp': 'iraníes' }, 
    'Irlanda': {'ms': 'irlandés', 'fs': 'irlandesa', 'mp': 'irlandeses', 'fp': 'irlandesas' }, 
    'Islandia': {'ms': 'islandés', 'fs': 'islandesa', 'mp': 'islandeses', 'fp': 'islandesas' }, 
    'Islas Marshall': {'ms': 'marshalés', 'fs': 'marshalesa', 'mp': 'marshaleses', 'fp': 'marshalesas' }, 
    'Islas Salomón': {'ms': 'salomonense', 'fs': 'salomonense', 'mp': 'salomonenses', 'fp': 'salomonenses' }, 
    'Israel': {'ms': 'israelí', 'fs': 'israelí', 'mp': 'israelíes', 'fp': 'israelíes' }, 
    'Italia': {'ms': 'italiano', 'fs': 'italiana', 'mp': 'italianos', 'fp': 'italianas' }, 
    'Jamaica': {'ms': 'jamaicano', 'fs': 'jamaicana', 'mp': 'jamaicanos', 'fp': 'jamaicanas' }, 
    'Japón': {'ms': 'japonés', 'fs': 'japonesa', 'mp': 'japoneses', 'fp': 'japonesas' }, 
    'Jordania': {'ms': 'jordano', 'fs': 'jordana', 'mp': 'jordanos', 'fp': 'jordanas' }, 
    'Kazajistán': {'ms': 'kazajo', 'fs': 'kazaja', 'mp': 'kazajos', 'fp': 'kazajas' }, 
    'Kenia': {'ms': 'keniano', 'fs': 'keniana', 'mp': 'kenianos', 'fp': 'kenianas' }, 
    'Kirguistán': {'ms': 'kirguís', 'fs': 'kirguís', 'mp': 'kirguises', 'fp': 'kirguisas' }, 
    'Kiribati': {'ms': 'kiribatiano', 'fs': 'kiribatiana', 'mp': 'kiribatianos', 'fp': 'kiribatianas' }, 
    'Kosovo': {'ms': 'kosovar', 'fs': 'kosovar', 'mp': 'kosovares', 'fp': 'kosovares' }, 
    'Kuwait': {'ms': 'kuwaití', 'fs': 'kuwaití', 'mp': 'kuwaitíes', 'fp': 'kuwaitíes' }, 
    'Laos': {'ms': 'laosiano', 'fs': 'laosiana', 'mp': 'laosianos', 'fp': 'laosianas' }, 
    'Lesoto': {'ms': 'lesotense', 'fs': 'lesotense', 'mp': 'lesotenses', 'fp': 'lesotenses' }, 
    'Letonia': {'ms': 'letón', 'fs': 'letona', 'mp': 'letones', 'fp': 'letonas' }, 
    'Líbano': {'ms': 'libanés', 'fs': 'libanesa', 'mp': 'libaneses', 'fp': 'libanesas' }, 
    'Liberia': {'ms': 'liberiano', 'fs': 'liberiana', 'mp': 'liberianos', 'fp': 'liberianas' }, 
    'Libia': {'ms': 'libio', 'fs': 'libia', 'mp': 'libios', 'fp': 'libias' }, 
    'Liechtenstein': {'ms': 'liechtensteiniano', 'fs': 'liechtensteiniana', 'mp': 'liechtensteinianos', 'fp': 'liechtensteinianas' }, 
    'Lituania': {'ms': 'lituano', 'fs': 'lituana', 'mp': 'lituanos', 'fp': 'lituanas' }, 
    'Luxemburgo': {'ms': 'luxemburgués', 'fs': 'luxemburguesa', 'mp': 'luxemburgueses', 'fp': 'luxemburguesas' }, 
    'Madagascar': {'ms': 'malgache', 'fs': 'malgache', 'mp': 'malgaches', 'fp': 'malgaches' }, 
    'Malasia': {'ms': 'malasio', 'fs': 'malasia', 'mp': 'malasios', 'fp': 'malasias' }, 
    'Malaui': {'ms': 'malauí', 'fs': 'malauí', 'mp': 'malauíes', 'fp': 'malauíes' }, 
    'Maldivas': {'ms': 'maldivo', 'fs': 'maldiva', 'mp': 'maldivos', 'fp': 'maldivas' }, 
    'Malí': {'ms': 'maliense', 'fs': 'maliense', 'mp': 'malienses', 'fp': 'malienses' }, 
    'Malta': {'ms': 'maltés', 'fs': 'maltesa', 'mp': 'malteses', 'fp': 'maltesas' }, 
    'Marruecos': {'ms': 'marroquí', 'fs': 'marroquí', 'mp': 'marroquíes', 'fp': 'marroquíes' }, 
    'Mauricio': {'ms': 'mauriciano', 'fs': 'mauriciana', 'mp': 'mauricianos', 'fp': 'mauricianas' }, 
    'Mauritania': {'ms': 'mauritano', 'fs': 'mauritana', 'mp': 'mauritanos', 'fp': 'mauritanas' }, 
    'México': {'ms': 'mexicano', 'fs': 'mexicana', 'mp': 'mexicanos', 'fp': 'mexicanas' }, 
    #'Micronesia': {'masculino': '', 'femenino': '' }, 
    'Moldavia': {'ms': 'moldavo', 'fs': 'moldava', 'mp': 'moldavos', 'fp': 'moldavas' }, 
    'Mónaco': {'ms': 'monegasco', 'fs': 'monegasca', 'mp': 'monegascos', 'fp': 'monegascas' }, 
    'Mongolia': {'ms': 'mongol', 'fs': 'mongola', 'mp': 'mongoles', 'fp': 'mongolas' }, 
    'Montenegro': {'ms': 'montenegrino', 'fs': 'montenegrina', 'mp': 'montenegrinos', 'fp': 'montenegrinas' }, 
    'Mozambique': {'ms': 'mozambiqueño', 'fs': 'mozambiqueña', 'mp': 'mozambiqueños', 'fp': 'mozambiqueñas' }, 
    'Namibia': {'ms': 'namibio', 'fs': 'namibia', 'mp': 'namibios', 'fp': 'namibias' }, 
    'Nauru': {'ms': 'nauruano', 'fs': 'nauruana', 'mp': 'nauruanos', 'fp': 'nauruanas' }, 
    'Nepal': {'ms': 'nepalés', 'fs': 'nepalesa', 'mp': 'nepaleses', 'fp': 'nepalesas' }, 
    'Nicaragua': {'ms': 'nicaragüense', 'fs': 'nicaragüense', 'mp': 'nicaragüenses', 'fp': 'nicaragüenses' }, 
    'Níger': {'ms': 'nigerino', 'fs': 'nigerina', 'mp': 'nigerinos', 'fp': 'nigerinas' }, 
    'Nigeria': {'ms': 'nigeriano', 'fs': 'nigeriana', 'mp': 'nigerianos', 'fp': 'nigerianas' }, 
    'Noruega': {'ms': 'noruego', 'fs': 'noruega', 'mp': 'noruegos', 'fp': 'noruegas' }, 
    'Nueva Zelanda': {'ms': 'neozelandés', 'fs': 'neozelandesa', 'mp': 'neozelandeses', 'fp': 'neozelandesas' }, 
    'Omán': {'ms': 'omaní', 'fs': 'omaní', 'mp': 'omaníes', 'fp': 'omaníes' }, 
    'Países Bajos': {'ms': 'neerlandés', 'fs': 'neerlandesa', 'mp': 'neerlandeses', 'fp': 'neerlandesas' }, 
    'Pakistán': {'ms': 'pakistaní', 'fs': 'pakistaní', 'mp': 'pakistaníes', 'fp': 'pakistaníes' }, 
    'Palaos': {'ms': 'palauano', 'fs': 'palauana', 'mp': 'palauanos', 'fp': 'palauanas' }, 
    'Panamá': {'ms': 'panameño', 'fs': 'panameña', 'mp': 'panameños', 'fp': 'panameñas' }, 
    'Papúa Nueva Guinea': {'ms': 'papú', 'fs': 'papú', 'mp': 'papúes', 'fp': 'papúes' }, 
    'Paraguay': {'ms': 'paraguayo', 'fs': 'paraguaya', 'mp': 'paraguayos', 'fp': 'paraguayas' }, 
    'Perú': {'ms': 'peruano', 'fs': 'peruana', 'mp': 'peruanos', 'fp': 'peruanas' }, 
    'Polonia': {'ms': 'polaco', 'fs': 'polaca', 'mp': 'polacos', 'fp': 'polacas' }, 
    'Portugal': {'ms': 'portugués', 'fs': 'portuguesa', 'mp': 'portugueses', 'fp': 'portuguesas' }, 
    'Reino Unido': {'ms': 'británico', 'fs': 'británica', 'mp': 'británicos', 'fp': 'británicas' }, 
    'República Árabe Saharaui Democrática': {'ms': 'saharaui', 'fs': 'saharaui', 'mp': 'saharauis', 'fp': 'saharauis' }, 
    'República Centroafricana': {'ms': 'centroafricano', 'fs': 'centroafricana', 'mp': 'centroafricanos', 'fp': 'centroafricanas' }, 
    'República Checa': {'ms': 'checo', 'fs': 'checa', 'mp': 'checos', 'fp': 'checas' }, 
    'República de China': {'ms': 'taiwanés', 'fs': 'taiwanesa', 'mp': 'taiwaneses', 'fp': 'taiwanesas' }, 
    'República de Macedonia': {'ms': 'macedonio', 'fs': 'macedonia', 'mp': 'macedonios', 'fp': 'macedonias' }, 
    'República del Congo': {'ms': 'congoleño', 'fs': 'congoleña', 'mp': 'congoleños', 'fp': 'congoleñas' }, 
    'República Democrática del Congo': {'ms': 'congoleño', 'fs': 'congoleña', 'mp': 'congoleños', 'fp': 'congoleñas' }, 
    'República Dominicana': {'ms': 'dominicano', 'fs': 'dominicana', 'mp': 'dominicanos', 'fp': 'dominicanas' }, 
    'República Popular China': {'ms': 'chino', 'fs': 'china', 'mp': 'chinos', 'fp': 'chinas' }, 
    'Ruanda': {'ms': 'ruandés', 'fs': 'ruandesa', 'mp': 'ruandeses', 'fp': 'ruandesas' }, 
    'Rumania': {'ms': 'rumano', 'fs': 'rumana', 'mp': 'rumanos', 'fp': 'rumanas' }, 
    'Rusia': {'ms': 'ruso', 'fs': 'rusa', 'mp': 'rusos', 'fp': 'rusas' }, 
    'Samoa': {'ms': 'samoano', 'fs': 'samoana', 'mp': 'samoanos', 'fp': 'samoanas' }, 
    'San Cristóbal y Nieves': {'ms': 'sancristobaleño', 'fs': 'sancristobaleña', 'mp': 'sancristobaleños', 'fp': 'sancristobaleñas' }, 
    'San Marino': {'ms': 'sanmarinense', 'fs': 'sanmarinense', 'mp': 'sanmarinenses', 'fp': 'sanmarinenses' }, 
    'San Vicente y las Granadinas': {'ms': 'sanvicentino', 'fs': 'sanvicentina', 'mp': 'sanvicentinos', 'fp': 'sanvicentinas' }, 
    'Santa Lucía': {'ms': 'santalucense', 'fs': 'santalucense', 'mp': 'santalucenses', 'fp': 'santalucenses' }, 
    'Santo Tomé y Príncipe': {'ms': 'santotomense', 'fs': 'santotomense', 'mp': 'santotomenses', 'fp': 'santotomenses' }, 
    'Senegal': {'ms': 'senegalés', 'fs': 'senegalesa', 'mp': 'senegaleses', 'fp': 'senegalesas' }, 
    'Serbia': {'ms': 'serbio', 'fs': 'serbia', 'mp': 'serbios', 'fp': 'serbias' }, 
    'Seychelles': {'ms': 'seychellense', 'fs': 'seychellense', 'mp': 'seychellenses', 'fp': 'seychellenses' }, 
    'Sierra Leona': {'ms': 'sierraleonés', 'fs': 'sierraleonesa', 'mp': 'sierraleoneses', 'fp': 'sierraleonesas' }, 
    'Singapur': {'ms': 'singapurense', 'fs': 'singapurense', 'mp': 'singapurenses', 'fp': 'singapurenses' }, 
    'Siria': {'ms': 'sirio', 'fs': 'siria', 'mp': 'sirios', 'fp': 'sirias' }, 
    'Somalia': {'ms': 'somalí', 'fs': 'somalí', 'mp': 'somalíes', 'fp': 'somalíes' }, 
    'Sri Lanka': {'ms': 'ceilanés', 'fs': 'ceilanesa', 'mp': 'ceilaneses', 'fp': 'ceilanesas' }, 
    'Suazilandia': {'ms': 'suazi', 'fs': 'suazi', 'mp': 'suazis', 'fp': 'suazis' }, 
    'Sudáfrica': {'ms': 'sudafricano', 'fs': 'sudafricana', 'mp': 'sudafricanos', 'fp': 'sudafricanas' }, 
    'Sudán': {'ms': 'sudanés', 'fs': 'sudanesa', 'mp': 'sudaneses', 'fp': 'sudanesas' }, 
    'Sudán del Sur': {'ms': 'sursudanés', 'fs': 'sursudanesa', 'mp': 'sursudaneses', 'fp': 'sursudanesas' }, 
    'Suecia': {'ms': 'sueco', 'fs': 'sueca', 'mp': 'suecos', 'fp': 'suecas' }, 
    'Suiza': {'ms': 'suizo', 'fs': 'suiza', 'mp': 'suizos', 'fp': 'suizas' }, 
    'Surinam': {'ms': 'surinamés', 'fs': 'surinamesa', 'mp': 'surinameses', 'fp': 'surinamesas' }, 
    'Tailandia': {'ms': 'tailandés', 'fs': 'tailandesa', 'mp': 'tailandeses', 'fp': 'tailandesas' }, 
    'Tanzania': {'ms': 'tanzano', 'fs': 'tanzana', 'mp': 'tanzanos', 'fp': 'tanzanas' }, 
    'Tayikistán': {'ms': 'tayiko', 'fs': 'tayika', 'mp': 'tayikos', 'fp': 'tayikas' }, 
    'Timor Oriental': {'ms': 'timorense', 'fs': 'timorense', 'mp': 'timorenses', 'fp': 'timorenses' }, 
    'Togo': {'ms': 'togolés', 'fs': 'togolesa', 'mp': 'togoleses', 'fp': 'togolesas' }, 
    'Tonga': {'ms': 'tongano', 'fs': 'tongana', 'mp': 'tonganos', 'fp': 'tonganas' }, 
    'Trinidad y Tobago': {'ms': 'trinitense', 'fs': 'trinitense', 'mp': 'trinitenses', 'fp': 'trinitenses' }, 
    'Túnez': {'ms': 'tunecino', 'fs': 'tunecina', 'mp': 'tunecinos', 'fp': 'tunecinas' }, 
    'Turkmenistán': {'ms': 'turcomano', 'fs': 'turcomana', 'mp': 'turcomanos', 'fp': 'turcomanas' }, 
    'Turquía': {'ms': 'turco', 'fs': 'turca', 'mp': 'turcos', 'fp': 'turcas' }, 
    'Tuvalu': {'ms': 'tuvaluano', 'fs': 'tuvaluana', 'mp': 'tuvaluanos', 'fp': 'tuvaluanas' }, 
    'Ucrania': {'ms': 'ucraniano', 'fs': 'ucraniana', 'mp': 'ucranianos', 'fp': 'ucranianas' }, 
    'Uganda': {'ms': 'ugandés', 'fs': 'ugandesa', 'mp': 'ugandeses', 'fp': 'ugandesas' }, 
    'Unión Soviética': {'ms': 'soviético', 'fs': 'soviética', 'mp': 'soviéticos', 'fp': 'soviéticas' }, 
    'Uruguay': {'ms': 'uruguayo', 'fs': 'uruguaya', 'mp': 'uruguayos', 'fp': 'uruguayas' }, 
    'Uzbekistán': {'ms': 'uzbeko', 'fs': 'uzbeka', 'mp': 'uzbekos', 'fp': 'uzbekas' }, 
    'Vanuatu': {'ms': 'vanuatuense', 'fs': 'vanuatuense', 'mp': 'vanuatuenses', 'fp': 'vanuatuenses' }, 
    'Venezuela': {'ms': 'venezolano', 'fs': 'venezolana', 'mp': 'venezolanos', 'fp': 'venezolanas' }, 
    'Vietnam': {'ms': 'vietnamita', 'fs': 'vietnamita', 'mp': 'vietnamitas', 'fp': 'vietnamitas' }, 
    'Yemen': {'ms': 'yemení', 'fs': 'yemení', 'mp': 'yemeníes', 'fp': 'yemeníes' }, 
    'Yibuti': {'ms': 'yibutiano', 'fs': 'yibutiana', 'mp': 'yibutianos', 'fp': 'yibutianas' }, 
    'Zambia': {'ms': 'zambiano', 'fs': 'zambiana', 'mp': 'zambianos', 'fp': 'zambianas' }, 
    'Zimbabue': {'ms': 'zimbabuense', 'fs': 'zimbabuense', 'mp': 'zimbabuenses', 'fp': 'zimbabuenses' }, 
}

paises2qid_list = [[k, v] for k, v in paises2qid.items()]
paises2qid_list.sort()

ocupaciones_list = [[k, v] for k, v in ocupaciones.items()]
ocupaciones_list.sort()

nacionalidades_list = [[k, v] for k, v in nacionalidades.items()]
nacionalidades_list.sort()

def getURL(url=''):
    raw = ''
    req = urllib.request.Request(url, headers={ 'User-Agent': 'Mozilla/5.0' })
    try:
        raw = urllib.request.urlopen(req).read().strip().decode('utf-8')
    except:
        sleep = 10 # seconds
        maxsleep = 100
        while sleep <= maxsleep:
            print('Error while retrieving: %s' % (url))
            print('Retry in %s seconds...' % (sleep))
            time.sleep(sleep)
            try:
                raw = urllib.request.urlopen(req).read().strip().decode('utf-8')
            except:
                pass
            sleep = sleep * 2
    return raw
